/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { OpperError } from "./oppererror.js";

export type UnauthorizedErrorData = {
  type?: string | undefined;
  message?: string | undefined;
  /**
   * The detail of the error
   */
  detail?: any | undefined;
};

export class UnauthorizedError extends OpperError {
  type?: string | undefined;
  /**
   * The detail of the error
   */
  detail?: any | undefined;

  /** The original data that was passed to this error instance. */
  data$: UnauthorizedErrorData;

  constructor(
    err: UnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.type != null) this.type = err.type;
    if (err.detail != null) this.detail = err.detail;

    this.name = "UnauthorizedError";
  }
}

/** @internal */
export const UnauthorizedError$inboundSchema: z.ZodType<
  UnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.string().default("UnauthorizedError"),
  message: z.string().default("The request is unauthorized"),
  detail: z.any().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new UnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type UnauthorizedError$Outbound = {
  type?: string;
  message?: string;
  detail?: any | undefined;
};

/** @internal */
export const UnauthorizedError$outboundSchema: z.ZodType<
  UnauthorizedError$Outbound,
  z.ZodTypeDef,
  UnauthorizedError
> = z.instanceof(UnauthorizedError)
  .transform(v => v.data$)
  .pipe(z.object({
    type: z.string().default("UnauthorizedError"),
    message: z.string().default("The request is unauthorized"),
    detail: z.any().optional(),
  }));
