/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { datasetsEntriesUpdate } from "../../funcs/datasetsEntriesUpdate.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  datasetId: z.string(),
  entryId: z.string(),
  updateDatasetEntryRequest: models.UpdateDatasetEntryRequest$inboundSchema,
};

export const tool$datasetsEntriesUpdate: ToolDefinition<typeof args> = {
  name: "datasets-entries-update",
  description: `Update Dataset Entry`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await datasetsEntriesUpdate(
      client,
      args.datasetId,
      args.entryId,
      args.updateDatasetEntryRequest,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
