/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { datasetsGetEntry } from "../../funcs/datasetsGetEntry.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  datasetId: z.string(),
  entryId: z.string(),
};

export const tool$datasetsGetEntry: ToolDefinition<typeof args> = {
  name: "datasets-get-entry",
  description: `Get Dataset Entry`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await datasetsGetEntry(
      client,
      args.datasetId,
      args.entryId,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
