/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { functionsUpdate } from "../../funcs/functionsUpdate.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  functionId: z.string(),
  updateFunctionRequest: models.UpdateFunctionRequest$inboundSchema,
};

export const tool$functionsUpdate: ToolDefinition<typeof args> = {
  name: "functions-update",
  description: `Update Function

Update a function, this will create a new revision of the function`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await functionsUpdate(
      client,
      args.functionId,
      args.updateFunctionRequest,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
