/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { knowledgeListFilesKnowledgeKnowledgeBaseIdFilesGet } from "../../funcs/knowledgeListFilesKnowledgeKnowledgeBaseIdFilesGet.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  knowledgeBaseId: z.string(),
  offset: z.number().int().default(0),
  limit: z.number().int().default(100),
};

export const tool$knowledgeListFilesKnowledgeKnowledgeBaseIdFilesGet:
  ToolDefinition<typeof args> = {
    name: "knowledge-list-files-knowledge-knowledge-base-id-files-get",
    description: `List Files

List all files in a knowledge base`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await knowledgeListFilesKnowledgeKnowledgeBaseIdFilesGet(
          client,
          args.knowledgeBaseId,
          args.offset,
          args.limit,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
