/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { knowledgeGet } from "../../funcs/knowledgeGet.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  knowledgeBaseId: z.string(),
};

export const tool$knowledgeGet: ToolDefinition<typeof args> = {
  name: "knowledge-get",
  description: `Get Knowledge Base

Get a knowledge base by its id`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await knowledgeGet(
      client,
      args.knowledgeBaseId,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
