/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { knowledgeUploadFileKnowledgeKnowledgeBaseIdUploadPost } from "../../funcs/knowledgeUploadFileKnowledgeKnowledgeBaseIdUploadPost.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  knowledgeBaseId: z.string(),
  bodyUploadFileKnowledgeKnowledgeBaseIdUploadPost:
    models.BodyUploadFileKnowledgeKnowledgeBaseIdUploadPost$inboundSchema,
};

export const tool$knowledgeUploadFileKnowledgeKnowledgeBaseIdUploadPost:
  ToolDefinition<typeof args> = {
    name: "knowledge-upload-file-knowledge-knowledge-base-id-upload-post",
    description: `Upload File

Upload a file directly to a knowledge base.

This is a simplified alternative to the three-step upload process
(get_upload_url -> upload to S3 -> register_file). Use this endpoint
for smaller files or when you prefer a simpler API.

The file will be uploaded to S3 and queued for processing automatically.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await knowledgeUploadFileKnowledgeKnowledgeBaseIdUploadPost(
          client,
          args.knowledgeBaseId,
          args.bodyUploadFileKnowledgeKnowledgeBaseIdUploadPost,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
