/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { knowledgeRegisterFileUpload } from "../../funcs/knowledgeRegisterFileUpload.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  knowledgeBaseId: z.string(),
  registerFileUploadRequest: models.RegisterFileUploadRequest$inboundSchema,
};

export const tool$knowledgeRegisterFileUpload: ToolDefinition<typeof args> = {
  name: "knowledge-register-file-upload",
  description: `Register File Upload

Register a file upload for a knowledge base by its id

Registering a file upload is a three step process:
1. Get upload URL (GET /v2/knowledge/{knowledge_base_id}/upload_url)
2. Upload file to the URL
3. Register file (POST /v2/knowledge/{knowledge_base_id}/register_file)`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await knowledgeRegisterFileUpload(
      client,
      args.knowledgeBaseId,
      args.registerFileUploadRequest,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
