/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { knowledgeGetFileDownloadUrl } from "../../funcs/knowledgeGetFileDownloadUrl.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  knowledgeBaseId: z.string(),
  fileId: z.string(),
};

export const tool$knowledgeGetFileDownloadUrl: ToolDefinition<typeof args> = {
  name: "knowledge-get-file-download-url",
  description: `Get File Download Url

Get a presigned URL to download a file from a knowledge base`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await knowledgeGetFileDownloadUrl(
      client,
      args.knowledgeBaseId,
      args.fileId,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
