/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { knowledgeCreat } from "../../funcs/knowledgeCreat.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.CreateKnowledgeBaseRequest$inboundSchema,
};

export const tool$knowledgeCreat: ToolDefinition<typeof args> = {
  name: "knowledge-creat",
  description: `Create Knowledge Base

Create a knowledge base`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await knowledgeCreat(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
