/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { knowledgeGetFileDownloadUrlKnowledgeKnowledgeBaseIdFilesFileIdDownloadUrlGet } from "../../funcs/knowledgeGetFileDownloadUrlKnowledgeKnowledgeBaseIdFilesFileIdDownloadUrlGet.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  knowledgeBaseId: z.string(),
  fileId: z.string(),
};

export const tool$knowledgeGetFileDownloadUrlKnowledgeKnowledgeBaseIdFilesFileIdDownloadUrlGet:
  ToolDefinition<typeof args> = {
    name:
      "knowledge-get-file-download-url-knowledge-knowledge-base-id-files-file-id-download-url-get",
    description: `Get File Download Url

Get a presigned URL to download a file from a knowledge base`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await knowledgeGetFileDownloadUrlKnowledgeKnowledgeBaseIdFilesFileIdDownloadUrlGet(
          client,
          args.knowledgeBaseId,
          args.fileId,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
