/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { languageModelsGetCustomByName } from "../../funcs/languageModelsGetCustomByName.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  name: z.string(),
};

export const tool$languageModelsGetCustomByName: ToolDefinition<typeof args> = {
  name: "language-models-get-custom-by-name",
  description: `Get Custom Model By Name

Get a custom language model by its name.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await languageModelsGetCustomByName(
      client,
      args.name,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
