/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { languageModelsListAliases } from "../../funcs/languageModelsListAliases.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  offset: z.number().int().default(0),
  limit: z.number().int().default(100),
};

export const tool$languageModelsListAliases: ToolDefinition<typeof args> = {
  name: "language-models-list-aliases",
  description: `List Model Aliases

List all model aliases for the organization that owns the API key.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await languageModelsListAliases(
      client,
      args.offset,
      args.limit,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
