/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { languageModelsList } from "../../funcs/languageModelsList.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  offset: z.number().int().default(0),
  limit: z.number().int().default(100),
};

export const tool$languageModelsList: ToolDefinition<typeof args> = {
  name: "language-models-list",
  description: `List Models

List all language models available in the Opper platform

For more information on the models available, see the [Opper Models](https://docs.opper.ai/capabilities/models) documentation.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await languageModelsList(
      client,
      args.offset,
      args.limit,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
