/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { languageModelsUpdateCustom } from "../../funcs/languageModelsUpdateCustom.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  modelId: z.string(),
  updateCustomModelRequest: models.UpdateCustomModelRequest$inboundSchema,
};

export const tool$languageModelsUpdateCustom: ToolDefinition<typeof args> = {
  name: "language-models-update-custom",
  description: `Update Custom Model

Update a custom language model.

If identifier, api_key, or extra are changed, the model configuration
is validated by making a test API call before saving.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await languageModelsUpdateCustom(
      client,
      args.modelId,
      args.updateCustomModelRequest,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
