/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { languageModelsGetAlias } from "../../funcs/languageModelsGetAlias.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  aliasId: z.string(),
};

export const tool$languageModelsGetAlias: ToolDefinition<typeof args> = {
  name: "language-models-get-alias",
  description: `Get Model Alias

Get a model alias by its ID.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await languageModelsGetAlias(
      client,
      args.aliasId,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
