/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ocrListOcrModelsOcrModelsGet } from "../../funcs/ocrListOcrModelsOcrModelsGet.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$ocrListOcrModelsOcrModelsGet: ToolDefinition = {
  name: "ocr-list-ocr-models-ocr-models-get",
  description: `List Ocr Models

List all available OCR models.

Returns a list of all OCR models available on the Opper platform,
including their hosting providers, locations, and pricing information.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await ocrListOcrModelsOcrModelsGet(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
