/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ocrProcessOcrOcrPost } from "../../funcs/ocrProcessOcrOcrPost.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.OCRRequestModel$inboundSchema,
};

export const tool$ocrProcessOcrOcrPost: ToolDefinition<typeof args> = {
  name: "ocr-process-ocr-ocr-post",
  description: `Process Ocr

Process a document using OCR (Optical Character Recognition).

This endpoint extracts text and structure from documents (PDFs, images) and
returns the content in markdown format. It supports multiple document types
and can extract images embedded within documents.

The extracted markdown preserves document structure including headings,
tables, lists, and other formatting.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await ocrProcessOcrOcrPost(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
