/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { rerankRerankDocumentsRerankPost } from "../../funcs/rerankRerankDocumentsRerankPost.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.RerankRequestModel$inboundSchema,
};

export const tool$rerankRerankDocumentsRerankPost: ToolDefinition<typeof args> =
  {
    name: "rerank-rerank-documents-rerank-post",
    description: `Rerank Documents

Rerank documents based on relevance to a query.

This endpoint allows you to rerank a list of documents based on their relevance
to a given query using state-of-the-art reranking models.

The documents will be returned in order of relevance, with the most relevant
documents first. Each result includes the original document index and a
relevance score.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await rerankRerankDocumentsRerankPost(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
