/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { spansGet } from "../../funcs/spansGet.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  spanId: z.string(),
};

export const tool$spansGet: ToolDefinition<typeof args> = {
  name: "spans-get",
  description: `Get Span

Get a span`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await spansGet(
      client,
      args.spanId,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
