/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { spansUpdate } from "../../funcs/spansUpdate.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  spanId: z.string(),
  updateSpanRequest: models.UpdateSpanRequest$inboundSchema,
};

export const tool$spansUpdate: ToolDefinition<typeof args> = {
  name: "spans-update",
  description: `Update Span

Update a span`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await spansUpdate(
      client,
      args.spanId,
      args.updateSpanRequest,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
