/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { spansCreate } from "../../funcs/spansCreate.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.CreateSpanRequest$inboundSchema,
};

export const tool$spansCreate: ToolDefinition<typeof args> = {
  name: "spans-create",
  description: `Create Span

Create a new span`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await spansCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
