/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { analyticsGetUsage } from "../funcs/analyticsGetUsage.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Analytics extends ClientSDK {
  /**
   * Usage
   */
  async getUsage(
    fromDate?: Date | null | undefined,
    toDate?: Date | null | undefined,
    granularity?: models.Granularity | null | undefined,
    fields?: Array<string> | null | undefined,
    groupBy?: Array<string> | null | undefined,
    options?: RequestOptions,
  ): Promise<Array<models.GetUsageResultItem>> {
    return unwrapAsync(analyticsGetUsage(
      this,
      fromDate,
      toDate,
      granularity,
      fields,
      groupBy,
      options,
    ));
  }
}
