/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { functionConfigGetFunctionConfigFunctionsFunctionIdConfigGet } from "../funcs/functionConfigGetFunctionConfigFunctionsFunctionIdConfigGet.js";
import { functionConfigPutSteeringFunctionsFunctionIdConfigSteeringPut } from "../funcs/functionConfigPutSteeringFunctionsFunctionIdConfigSteeringPut.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class FunctionConfig extends ClientSDK {
  /**
   * Get Function Config
   */
  async getFunctionConfigFunctionsFunctionIdConfigGet(
    functionId: string,
    options?: RequestOptions,
  ): Promise<models.FunctionConfigResponse> {
    return unwrapAsync(
      functionConfigGetFunctionConfigFunctionsFunctionIdConfigGet(
        this,
        functionId,
        options,
      ),
    );
  }

  /**
   * Put Steering
   */
  async putSteeringFunctionsFunctionIdConfigSteeringPut(
    functionId: string,
    steeringConfig: models.SteeringConfig,
    options?: RequestOptions,
  ): Promise<{ [k: string]: any }> {
    return unwrapAsync(
      functionConfigPutSteeringFunctionsFunctionIdConfigSteeringPut(
        this,
        functionId,
        steeringConfig,
        options,
      ),
    );
  }
}
