/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type Payload =
  | models.ChatCompletionStreaming
  | models.ChatCompletionNonStreaming;

/** @internal */
export const Payload$inboundSchema: z.ZodType<Payload, z.ZodTypeDef, unknown> =
  z.union([
    models.ChatCompletionStreaming$inboundSchema,
    models.ChatCompletionNonStreaming$inboundSchema,
  ]);
/** @internal */
export type Payload$Outbound =
  | models.ChatCompletionStreaming$Outbound
  | models.ChatCompletionNonStreaming$Outbound;

/** @internal */
export const Payload$outboundSchema: z.ZodType<
  Payload$Outbound,
  z.ZodTypeDef,
  Payload
> = z.union([
  models.ChatCompletionStreaming$outboundSchema,
  models.ChatCompletionNonStreaming$outboundSchema,
]);

export function payloadToJSON(payload: Payload): string {
  return JSON.stringify(Payload$outboundSchema.parse(payload));
}
export function payloadFromJSON(
  jsonString: string,
): SafeParseResult<Payload, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Payload$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Payload' from JSON`,
  );
}
