/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteSpanSpansSpanIdDeleteRequest = {
  /**
   * The ID of the span to delete
   */
  spanId: string;
};

/** @internal */
export const DeleteSpanSpansSpanIdDeleteRequest$inboundSchema: z.ZodType<
  DeleteSpanSpansSpanIdDeleteRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  span_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "span_id": "spanId",
  });
});
/** @internal */
export type DeleteSpanSpansSpanIdDeleteRequest$Outbound = {
  span_id: string;
};

/** @internal */
export const DeleteSpanSpansSpanIdDeleteRequest$outboundSchema: z.ZodType<
  DeleteSpanSpansSpanIdDeleteRequest$Outbound,
  z.ZodTypeDef,
  DeleteSpanSpansSpanIdDeleteRequest
> = z.object({
  spanId: z.string(),
}).transform((v) => {
  return remap$(v, {
    spanId: "span_id",
  });
});

export function deleteSpanSpansSpanIdDeleteRequestToJSON(
  deleteSpanSpansSpanIdDeleteRequest: DeleteSpanSpansSpanIdDeleteRequest,
): string {
  return JSON.stringify(
    DeleteSpanSpansSpanIdDeleteRequest$outboundSchema.parse(
      deleteSpanSpansSpanIdDeleteRequest,
    ),
  );
}
export function deleteSpanSpansSpanIdDeleteRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteSpanSpansSpanIdDeleteRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteSpanSpansSpanIdDeleteRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteSpanSpansSpanIdDeleteRequest' from JSON`,
  );
}
