/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteFileFromKnowledgeBaseKnowledgeKnowledgeBaseIdFilesFileIdDeleteRequest =
  {
    /**
     * The id of the knowledge base
     */
    knowledgeBaseId: string;
    /**
     * The id of the file to delete
     */
    fileId: string;
  };

/** @internal */
export const DeleteFileFromKnowledgeBaseKnowledgeKnowledgeBaseIdFilesFileIdDeleteRequest$inboundSchema:
  z.ZodType<
    DeleteFileFromKnowledgeBaseKnowledgeKnowledgeBaseIdFilesFileIdDeleteRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    knowledge_base_id: z.string(),
    file_id: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "knowledge_base_id": "knowledgeBaseId",
      "file_id": "fileId",
    });
  });

/** @internal */
export type DeleteFileFromKnowledgeBaseKnowledgeKnowledgeBaseIdFilesFileIdDeleteRequest$Outbound =
  {
    knowledge_base_id: string;
    file_id: string;
  };

/** @internal */
export const DeleteFileFromKnowledgeBaseKnowledgeKnowledgeBaseIdFilesFileIdDeleteRequest$outboundSchema:
  z.ZodType<
    DeleteFileFromKnowledgeBaseKnowledgeKnowledgeBaseIdFilesFileIdDeleteRequest$Outbound,
    z.ZodTypeDef,
    DeleteFileFromKnowledgeBaseKnowledgeKnowledgeBaseIdFilesFileIdDeleteRequest
  > = z.object({
    knowledgeBaseId: z.string(),
    fileId: z.string(),
  }).transform((v) => {
    return remap$(v, {
      knowledgeBaseId: "knowledge_base_id",
      fileId: "file_id",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteFileFromKnowledgeBaseKnowledgeKnowledgeBaseIdFilesFileIdDeleteRequest$ {
  /** @deprecated use `DeleteFileFromKnowledgeBaseKnowledgeKnowledgeBaseIdFilesFileIdDeleteRequest$inboundSchema` instead. */
  export const inboundSchema =
    DeleteFileFromKnowledgeBaseKnowledgeKnowledgeBaseIdFilesFileIdDeleteRequest$inboundSchema;
  /** @deprecated use `DeleteFileFromKnowledgeBaseKnowledgeKnowledgeBaseIdFilesFileIdDeleteRequest$outboundSchema` instead. */
  export const outboundSchema =
    DeleteFileFromKnowledgeBaseKnowledgeKnowledgeBaseIdFilesFileIdDeleteRequest$outboundSchema;
  /** @deprecated use `DeleteFileFromKnowledgeBaseKnowledgeKnowledgeBaseIdFilesFileIdDeleteRequest$Outbound` instead. */
  export type Outbound =
    DeleteFileFromKnowledgeBaseKnowledgeKnowledgeBaseIdFilesFileIdDeleteRequest$Outbound;
}

export function deleteFileFromKnowledgeBaseKnowledgeKnowledgeBaseIdFilesFileIdDeleteRequestToJSON(
  deleteFileFromKnowledgeBaseKnowledgeKnowledgeBaseIdFilesFileIdDeleteRequest:
    DeleteFileFromKnowledgeBaseKnowledgeKnowledgeBaseIdFilesFileIdDeleteRequest,
): string {
  return JSON.stringify(
    DeleteFileFromKnowledgeBaseKnowledgeKnowledgeBaseIdFilesFileIdDeleteRequest$outboundSchema
      .parse(
        deleteFileFromKnowledgeBaseKnowledgeKnowledgeBaseIdFilesFileIdDeleteRequest,
      ),
  );
}

export function deleteFileFromKnowledgeBaseKnowledgeKnowledgeBaseIdFilesFileIdDeleteRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteFileFromKnowledgeBaseKnowledgeKnowledgeBaseIdFilesFileIdDeleteRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteFileFromKnowledgeBaseKnowledgeKnowledgeBaseIdFilesFileIdDeleteRequest$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'DeleteFileFromKnowledgeBaseKnowledgeKnowledgeBaseIdFilesFileIdDeleteRequest' from JSON`,
  );
}
