/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteMetricSpansSpanIdMetricsMetricIdDeleteRequest = {
  spanId: string;
  metricId: string;
};

/** @internal */
export const DeleteMetricSpansSpanIdMetricsMetricIdDeleteRequest$inboundSchema:
  z.ZodType<
    DeleteMetricSpansSpanIdMetricsMetricIdDeleteRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    span_id: z.string(),
    metric_id: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "span_id": "spanId",
      "metric_id": "metricId",
    });
  });

/** @internal */
export type DeleteMetricSpansSpanIdMetricsMetricIdDeleteRequest$Outbound = {
  span_id: string;
  metric_id: string;
};

/** @internal */
export const DeleteMetricSpansSpanIdMetricsMetricIdDeleteRequest$outboundSchema:
  z.ZodType<
    DeleteMetricSpansSpanIdMetricsMetricIdDeleteRequest$Outbound,
    z.ZodTypeDef,
    DeleteMetricSpansSpanIdMetricsMetricIdDeleteRequest
  > = z.object({
    spanId: z.string(),
    metricId: z.string(),
  }).transform((v) => {
    return remap$(v, {
      spanId: "span_id",
      metricId: "metric_id",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteMetricSpansSpanIdMetricsMetricIdDeleteRequest$ {
  /** @deprecated use `DeleteMetricSpansSpanIdMetricsMetricIdDeleteRequest$inboundSchema` instead. */
  export const inboundSchema =
    DeleteMetricSpansSpanIdMetricsMetricIdDeleteRequest$inboundSchema;
  /** @deprecated use `DeleteMetricSpansSpanIdMetricsMetricIdDeleteRequest$outboundSchema` instead. */
  export const outboundSchema =
    DeleteMetricSpansSpanIdMetricsMetricIdDeleteRequest$outboundSchema;
  /** @deprecated use `DeleteMetricSpansSpanIdMetricsMetricIdDeleteRequest$Outbound` instead. */
  export type Outbound =
    DeleteMetricSpansSpanIdMetricsMetricIdDeleteRequest$Outbound;
}

export function deleteMetricSpansSpanIdMetricsMetricIdDeleteRequestToJSON(
  deleteMetricSpansSpanIdMetricsMetricIdDeleteRequest:
    DeleteMetricSpansSpanIdMetricsMetricIdDeleteRequest,
): string {
  return JSON.stringify(
    DeleteMetricSpansSpanIdMetricsMetricIdDeleteRequest$outboundSchema.parse(
      deleteMetricSpansSpanIdMetricsMetricIdDeleteRequest,
    ),
  );
}

export function deleteMetricSpansSpanIdMetricsMetricIdDeleteRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteMetricSpansSpanIdMetricsMetricIdDeleteRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteMetricSpansSpanIdMetricsMetricIdDeleteRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DeleteMetricSpansSpanIdMetricsMetricIdDeleteRequest' from JSON`,
  );
}
