/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetDatasetEntryDatasetsDatasetIdEntriesEntryIdGetRequest = {
  /**
   * The id of the dataset
   */
  datasetId: string;
  /**
   * The id of the entry to get
   */
  entryId: string;
};

/** @internal */
export const GetDatasetEntryDatasetsDatasetIdEntriesEntryIdGetRequest$inboundSchema:
  z.ZodType<
    GetDatasetEntryDatasetsDatasetIdEntriesEntryIdGetRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    dataset_id: z.string(),
    entry_id: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "dataset_id": "datasetId",
      "entry_id": "entryId",
    });
  });

/** @internal */
export type GetDatasetEntryDatasetsDatasetIdEntriesEntryIdGetRequest$Outbound =
  {
    dataset_id: string;
    entry_id: string;
  };

/** @internal */
export const GetDatasetEntryDatasetsDatasetIdEntriesEntryIdGetRequest$outboundSchema:
  z.ZodType<
    GetDatasetEntryDatasetsDatasetIdEntriesEntryIdGetRequest$Outbound,
    z.ZodTypeDef,
    GetDatasetEntryDatasetsDatasetIdEntriesEntryIdGetRequest
  > = z.object({
    datasetId: z.string(),
    entryId: z.string(),
  }).transform((v) => {
    return remap$(v, {
      datasetId: "dataset_id",
      entryId: "entry_id",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetDatasetEntryDatasetsDatasetIdEntriesEntryIdGetRequest$ {
  /** @deprecated use `GetDatasetEntryDatasetsDatasetIdEntriesEntryIdGetRequest$inboundSchema` instead. */
  export const inboundSchema =
    GetDatasetEntryDatasetsDatasetIdEntriesEntryIdGetRequest$inboundSchema;
  /** @deprecated use `GetDatasetEntryDatasetsDatasetIdEntriesEntryIdGetRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetDatasetEntryDatasetsDatasetIdEntriesEntryIdGetRequest$outboundSchema;
  /** @deprecated use `GetDatasetEntryDatasetsDatasetIdEntriesEntryIdGetRequest$Outbound` instead. */
  export type Outbound =
    GetDatasetEntryDatasetsDatasetIdEntriesEntryIdGetRequest$Outbound;
}

export function getDatasetEntryDatasetsDatasetIdEntriesEntryIdGetRequestToJSON(
  getDatasetEntryDatasetsDatasetIdEntriesEntryIdGetRequest:
    GetDatasetEntryDatasetsDatasetIdEntriesEntryIdGetRequest,
): string {
  return JSON.stringify(
    GetDatasetEntryDatasetsDatasetIdEntriesEntryIdGetRequest$outboundSchema
      .parse(getDatasetEntryDatasetsDatasetIdEntriesEntryIdGetRequest),
  );
}

export function getDatasetEntryDatasetsDatasetIdEntriesEntryIdGetRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  GetDatasetEntryDatasetsDatasetIdEntriesEntryIdGetRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetDatasetEntryDatasetsDatasetIdEntriesEntryIdGetRequest$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetDatasetEntryDatasetsDatasetIdEntriesEntryIdGetRequest' from JSON`,
  );
}
