/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetFunctionConfigFunctionsFunctionIdConfigGetRequest = {
  /**
   * The id of the function whose config to retrieve
   */
  functionId: string;
};

/** @internal */
export const GetFunctionConfigFunctionsFunctionIdConfigGetRequest$inboundSchema:
  z.ZodType<
    GetFunctionConfigFunctionsFunctionIdConfigGetRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    function_id: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "function_id": "functionId",
    });
  });
/** @internal */
export type GetFunctionConfigFunctionsFunctionIdConfigGetRequest$Outbound = {
  function_id: string;
};

/** @internal */
export const GetFunctionConfigFunctionsFunctionIdConfigGetRequest$outboundSchema:
  z.ZodType<
    GetFunctionConfigFunctionsFunctionIdConfigGetRequest$Outbound,
    z.ZodTypeDef,
    GetFunctionConfigFunctionsFunctionIdConfigGetRequest
  > = z.object({
    functionId: z.string(),
  }).transform((v) => {
    return remap$(v, {
      functionId: "function_id",
    });
  });

export function getFunctionConfigFunctionsFunctionIdConfigGetRequestToJSON(
  getFunctionConfigFunctionsFunctionIdConfigGetRequest:
    GetFunctionConfigFunctionsFunctionIdConfigGetRequest,
): string {
  return JSON.stringify(
    GetFunctionConfigFunctionsFunctionIdConfigGetRequest$outboundSchema.parse(
      getFunctionConfigFunctionsFunctionIdConfigGetRequest,
    ),
  );
}
export function getFunctionConfigFunctionsFunctionIdConfigGetRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  GetFunctionConfigFunctionsFunctionIdConfigGetRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetFunctionConfigFunctionsFunctionIdConfigGetRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetFunctionConfigFunctionsFunctionIdConfigGetRequest' from JSON`,
  );
}
