/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetFileDownloadUrlKnowledgeKnowledgeBaseIdFilesFileIdDownloadUrlGetRequest =
  {
    /**
     * The id of the knowledge base
     */
    knowledgeBaseId: string;
    /**
     * The id of the file
     */
    fileId: string;
  };

/** @internal */
export const GetFileDownloadUrlKnowledgeKnowledgeBaseIdFilesFileIdDownloadUrlGetRequest$inboundSchema:
  z.ZodType<
    GetFileDownloadUrlKnowledgeKnowledgeBaseIdFilesFileIdDownloadUrlGetRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    knowledge_base_id: z.string(),
    file_id: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "knowledge_base_id": "knowledgeBaseId",
      "file_id": "fileId",
    });
  });
/** @internal */
export type GetFileDownloadUrlKnowledgeKnowledgeBaseIdFilesFileIdDownloadUrlGetRequest$Outbound =
  {
    knowledge_base_id: string;
    file_id: string;
  };

/** @internal */
export const GetFileDownloadUrlKnowledgeKnowledgeBaseIdFilesFileIdDownloadUrlGetRequest$outboundSchema:
  z.ZodType<
    GetFileDownloadUrlKnowledgeKnowledgeBaseIdFilesFileIdDownloadUrlGetRequest$Outbound,
    z.ZodTypeDef,
    GetFileDownloadUrlKnowledgeKnowledgeBaseIdFilesFileIdDownloadUrlGetRequest
  > = z.object({
    knowledgeBaseId: z.string(),
    fileId: z.string(),
  }).transform((v) => {
    return remap$(v, {
      knowledgeBaseId: "knowledge_base_id",
      fileId: "file_id",
    });
  });

export function getFileDownloadUrlKnowledgeKnowledgeBaseIdFilesFileIdDownloadUrlGetRequestToJSON(
  getFileDownloadUrlKnowledgeKnowledgeBaseIdFilesFileIdDownloadUrlGetRequest:
    GetFileDownloadUrlKnowledgeKnowledgeBaseIdFilesFileIdDownloadUrlGetRequest,
): string {
  return JSON.stringify(
    GetFileDownloadUrlKnowledgeKnowledgeBaseIdFilesFileIdDownloadUrlGetRequest$outboundSchema
      .parse(
        getFileDownloadUrlKnowledgeKnowledgeBaseIdFilesFileIdDownloadUrlGetRequest,
      ),
  );
}
export function getFileDownloadUrlKnowledgeKnowledgeBaseIdFilesFileIdDownloadUrlGetRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  GetFileDownloadUrlKnowledgeKnowledgeBaseIdFilesFileIdDownloadUrlGetRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetFileDownloadUrlKnowledgeKnowledgeBaseIdFilesFileIdDownloadUrlGetRequest$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetFileDownloadUrlKnowledgeKnowledgeBaseIdFilesFileIdDownloadUrlGetRequest' from JSON`,
  );
}
