/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetMetricSpansSpanIdMetricsMetricIdGetRequest = {
  /**
   * The id of the span
   */
  spanId: string;
  /**
   * The id of the metric to get
   */
  metricId: string;
};

/** @internal */
export const GetMetricSpansSpanIdMetricsMetricIdGetRequest$inboundSchema:
  z.ZodType<
    GetMetricSpansSpanIdMetricsMetricIdGetRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    span_id: z.string(),
    metric_id: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "span_id": "spanId",
      "metric_id": "metricId",
    });
  });

/** @internal */
export type GetMetricSpansSpanIdMetricsMetricIdGetRequest$Outbound = {
  span_id: string;
  metric_id: string;
};

/** @internal */
export const GetMetricSpansSpanIdMetricsMetricIdGetRequest$outboundSchema:
  z.ZodType<
    GetMetricSpansSpanIdMetricsMetricIdGetRequest$Outbound,
    z.ZodTypeDef,
    GetMetricSpansSpanIdMetricsMetricIdGetRequest
  > = z.object({
    spanId: z.string(),
    metricId: z.string(),
  }).transform((v) => {
    return remap$(v, {
      spanId: "span_id",
      metricId: "metric_id",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetMetricSpansSpanIdMetricsMetricIdGetRequest$ {
  /** @deprecated use `GetMetricSpansSpanIdMetricsMetricIdGetRequest$inboundSchema` instead. */
  export const inboundSchema =
    GetMetricSpansSpanIdMetricsMetricIdGetRequest$inboundSchema;
  /** @deprecated use `GetMetricSpansSpanIdMetricsMetricIdGetRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetMetricSpansSpanIdMetricsMetricIdGetRequest$outboundSchema;
  /** @deprecated use `GetMetricSpansSpanIdMetricsMetricIdGetRequest$Outbound` instead. */
  export type Outbound = GetMetricSpansSpanIdMetricsMetricIdGetRequest$Outbound;
}

export function getMetricSpansSpanIdMetricsMetricIdGetRequestToJSON(
  getMetricSpansSpanIdMetricsMetricIdGetRequest:
    GetMetricSpansSpanIdMetricsMetricIdGetRequest,
): string {
  return JSON.stringify(
    GetMetricSpansSpanIdMetricsMetricIdGetRequest$outboundSchema.parse(
      getMetricSpansSpanIdMetricsMetricIdGetRequest,
    ),
  );
}

export function getMetricSpansSpanIdMetricsMetricIdGetRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  GetMetricSpansSpanIdMetricsMetricIdGetRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetMetricSpansSpanIdMetricsMetricIdGetRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetMetricSpansSpanIdMetricsMetricIdGetRequest' from JSON`,
  );
}
