/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListCustomModelsModelsCustomGetRequest = {
  /**
   * The offset of the first model to return
   */
  offset?: number | undefined;
  /**
   * The maximum number of models to return
   */
  limit?: number | undefined;
};

/** @internal */
export const ListCustomModelsModelsCustomGetRequest$inboundSchema: z.ZodType<
  ListCustomModelsModelsCustomGetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  offset: z.number().int().default(0),
  limit: z.number().int().default(100),
});

/** @internal */
export type ListCustomModelsModelsCustomGetRequest$Outbound = {
  offset: number;
  limit: number;
};

/** @internal */
export const ListCustomModelsModelsCustomGetRequest$outboundSchema: z.ZodType<
  ListCustomModelsModelsCustomGetRequest$Outbound,
  z.ZodTypeDef,
  ListCustomModelsModelsCustomGetRequest
> = z.object({
  offset: z.number().int().default(0),
  limit: z.number().int().default(100),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListCustomModelsModelsCustomGetRequest$ {
  /** @deprecated use `ListCustomModelsModelsCustomGetRequest$inboundSchema` instead. */
  export const inboundSchema =
    ListCustomModelsModelsCustomGetRequest$inboundSchema;
  /** @deprecated use `ListCustomModelsModelsCustomGetRequest$outboundSchema` instead. */
  export const outboundSchema =
    ListCustomModelsModelsCustomGetRequest$outboundSchema;
  /** @deprecated use `ListCustomModelsModelsCustomGetRequest$Outbound` instead. */
  export type Outbound = ListCustomModelsModelsCustomGetRequest$Outbound;
}

export function listCustomModelsModelsCustomGetRequestToJSON(
  listCustomModelsModelsCustomGetRequest:
    ListCustomModelsModelsCustomGetRequest,
): string {
  return JSON.stringify(
    ListCustomModelsModelsCustomGetRequest$outboundSchema.parse(
      listCustomModelsModelsCustomGetRequest,
    ),
  );
}

export function listCustomModelsModelsCustomGetRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListCustomModelsModelsCustomGetRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ListCustomModelsModelsCustomGetRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListCustomModelsModelsCustomGetRequest' from JSON`,
  );
}
