/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type RegisterFileUploadKnowledgeKnowledgeBaseIdRegisterFilePostRequest =
  {
    /**
     * The id of the knowledge base to register the file for
     */
    knowledgeBaseId: string;
    registerFileUploadRequest: models.RegisterFileUploadRequest;
  };

/** @internal */
export const RegisterFileUploadKnowledgeKnowledgeBaseIdRegisterFilePostRequest$inboundSchema:
  z.ZodType<
    RegisterFileUploadKnowledgeKnowledgeBaseIdRegisterFilePostRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    knowledge_base_id: z.string(),
    RegisterFileUploadRequest: models.RegisterFileUploadRequest$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "knowledge_base_id": "knowledgeBaseId",
      "RegisterFileUploadRequest": "registerFileUploadRequest",
    });
  });

/** @internal */
export type RegisterFileUploadKnowledgeKnowledgeBaseIdRegisterFilePostRequest$Outbound =
  {
    knowledge_base_id: string;
    RegisterFileUploadRequest: models.RegisterFileUploadRequest$Outbound;
  };

/** @internal */
export const RegisterFileUploadKnowledgeKnowledgeBaseIdRegisterFilePostRequest$outboundSchema:
  z.ZodType<
    RegisterFileUploadKnowledgeKnowledgeBaseIdRegisterFilePostRequest$Outbound,
    z.ZodTypeDef,
    RegisterFileUploadKnowledgeKnowledgeBaseIdRegisterFilePostRequest
  > = z.object({
    knowledgeBaseId: z.string(),
    registerFileUploadRequest: models.RegisterFileUploadRequest$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      knowledgeBaseId: "knowledge_base_id",
      registerFileUploadRequest: "RegisterFileUploadRequest",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RegisterFileUploadKnowledgeKnowledgeBaseIdRegisterFilePostRequest$ {
  /** @deprecated use `RegisterFileUploadKnowledgeKnowledgeBaseIdRegisterFilePostRequest$inboundSchema` instead. */
  export const inboundSchema =
    RegisterFileUploadKnowledgeKnowledgeBaseIdRegisterFilePostRequest$inboundSchema;
  /** @deprecated use `RegisterFileUploadKnowledgeKnowledgeBaseIdRegisterFilePostRequest$outboundSchema` instead. */
  export const outboundSchema =
    RegisterFileUploadKnowledgeKnowledgeBaseIdRegisterFilePostRequest$outboundSchema;
  /** @deprecated use `RegisterFileUploadKnowledgeKnowledgeBaseIdRegisterFilePostRequest$Outbound` instead. */
  export type Outbound =
    RegisterFileUploadKnowledgeKnowledgeBaseIdRegisterFilePostRequest$Outbound;
}

export function registerFileUploadKnowledgeKnowledgeBaseIdRegisterFilePostRequestToJSON(
  registerFileUploadKnowledgeKnowledgeBaseIdRegisterFilePostRequest:
    RegisterFileUploadKnowledgeKnowledgeBaseIdRegisterFilePostRequest,
): string {
  return JSON.stringify(
    RegisterFileUploadKnowledgeKnowledgeBaseIdRegisterFilePostRequest$outboundSchema
      .parse(registerFileUploadKnowledgeKnowledgeBaseIdRegisterFilePostRequest),
  );
}

export function registerFileUploadKnowledgeKnowledgeBaseIdRegisterFilePostRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  RegisterFileUploadKnowledgeKnowledgeBaseIdRegisterFilePostRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      RegisterFileUploadKnowledgeKnowledgeBaseIdRegisterFilePostRequest$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'RegisterFileUploadKnowledgeKnowledgeBaseIdRegisterFilePostRequest' from JSON`,
  );
}
