/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type AppApiPublicV2FunctionsCallFunctionResponse = {
  spanId?: string | null | undefined;
  message?: string | null | undefined;
  jsonPayload?: any | null | undefined;
  audio?: { [k: string]: any } | null | undefined;
  cached?: boolean | undefined;
};

/** @internal */
export const AppApiPublicV2FunctionsCallFunctionResponse$inboundSchema:
  z.ZodType<
    AppApiPublicV2FunctionsCallFunctionResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    span_id: z.nullable(z.string()).optional(),
    message: z.nullable(z.string()).optional(),
    json_payload: z.nullable(z.any()).optional(),
    audio: z.nullable(z.record(z.any())).optional(),
    cached: z.boolean().default(false),
  }).transform((v) => {
    return remap$(v, {
      "span_id": "spanId",
      "json_payload": "jsonPayload",
    });
  });

/** @internal */
export type AppApiPublicV2FunctionsCallFunctionResponse$Outbound = {
  span_id?: string | null | undefined;
  message?: string | null | undefined;
  json_payload?: any | null | undefined;
  audio?: { [k: string]: any } | null | undefined;
  cached: boolean;
};

/** @internal */
export const AppApiPublicV2FunctionsCallFunctionResponse$outboundSchema:
  z.ZodType<
    AppApiPublicV2FunctionsCallFunctionResponse$Outbound,
    z.ZodTypeDef,
    AppApiPublicV2FunctionsCallFunctionResponse
  > = z.object({
    spanId: z.nullable(z.string()).optional(),
    message: z.nullable(z.string()).optional(),
    jsonPayload: z.nullable(z.any()).optional(),
    audio: z.nullable(z.record(z.any())).optional(),
    cached: z.boolean().default(false),
  }).transform((v) => {
    return remap$(v, {
      spanId: "span_id",
      jsonPayload: "json_payload",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppApiPublicV2FunctionsCallFunctionResponse$ {
  /** @deprecated use `AppApiPublicV2FunctionsCallFunctionResponse$inboundSchema` instead. */
  export const inboundSchema =
    AppApiPublicV2FunctionsCallFunctionResponse$inboundSchema;
  /** @deprecated use `AppApiPublicV2FunctionsCallFunctionResponse$outboundSchema` instead. */
  export const outboundSchema =
    AppApiPublicV2FunctionsCallFunctionResponse$outboundSchema;
  /** @deprecated use `AppApiPublicV2FunctionsCallFunctionResponse$Outbound` instead. */
  export type Outbound = AppApiPublicV2FunctionsCallFunctionResponse$Outbound;
}

export function appApiPublicV2FunctionsCallFunctionResponseToJSON(
  appApiPublicV2FunctionsCallFunctionResponse:
    AppApiPublicV2FunctionsCallFunctionResponse,
): string {
  return JSON.stringify(
    AppApiPublicV2FunctionsCallFunctionResponse$outboundSchema.parse(
      appApiPublicV2FunctionsCallFunctionResponse,
    ),
  );
}

export function appApiPublicV2FunctionsCallFunctionResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  AppApiPublicV2FunctionsCallFunctionResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AppApiPublicV2FunctionsCallFunctionResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AppApiPublicV2FunctionsCallFunctionResponse' from JSON`,
  );
}
