/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  FunctionOutput,
  FunctionOutput$inboundSchema,
  FunctionOutput$Outbound,
  FunctionOutput$outboundSchema,
} from "./functionoutput.js";

export type ChatCompletionMessageFunctionToolCall = {
  id: string;
  function: FunctionOutput;
  type?: "function" | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

/** @internal */
export const ChatCompletionMessageFunctionToolCall$inboundSchema: z.ZodType<
  ChatCompletionMessageFunctionToolCall,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    id: z.string(),
    function: FunctionOutput$inboundSchema,
    type: z.literal("function").default("function").optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
);
/** @internal */
export type ChatCompletionMessageFunctionToolCall$Outbound = {
  id: string;
  function: FunctionOutput$Outbound;
  type: "function";
  [additionalProperties: string]: unknown;
};

/** @internal */
export const ChatCompletionMessageFunctionToolCall$outboundSchema: z.ZodType<
  ChatCompletionMessageFunctionToolCall$Outbound,
  z.ZodTypeDef,
  ChatCompletionMessageFunctionToolCall
> = z.object({
  id: z.string(),
  function: FunctionOutput$outboundSchema,
  type: z.literal("function"),
  additionalProperties: z.record(z.any()).optional(),
}).transform((v) => {
  return {
    ...v.additionalProperties,
    ...remap$(v, {
      additionalProperties: null,
    }),
  };
});

export function chatCompletionMessageFunctionToolCallToJSON(
  chatCompletionMessageFunctionToolCall: ChatCompletionMessageFunctionToolCall,
): string {
  return JSON.stringify(
    ChatCompletionMessageFunctionToolCall$outboundSchema.parse(
      chatCompletionMessageFunctionToolCall,
    ),
  );
}
export function chatCompletionMessageFunctionToolCallFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionMessageFunctionToolCall, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ChatCompletionMessageFunctionToolCall$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionMessageFunctionToolCall' from JSON`,
  );
}
