/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OpenaiTypesChatChatCompletionMessageCustomToolCallParamCustom,
  OpenaiTypesChatChatCompletionMessageCustomToolCallParamCustom$inboundSchema,
  OpenaiTypesChatChatCompletionMessageCustomToolCallParamCustom$Outbound,
  OpenaiTypesChatChatCompletionMessageCustomToolCallParamCustom$outboundSchema,
} from "./openaitypeschatchatcompletionmessagecustomtoolcallparamcustom.js";

export type ChatCompletionMessageCustomToolCallParam = {
  id: string;
  custom: OpenaiTypesChatChatCompletionMessageCustomToolCallParamCustom;
  type: "custom";
};

/** @internal */
export const ChatCompletionMessageCustomToolCallParam$inboundSchema: z.ZodType<
  ChatCompletionMessageCustomToolCallParam,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  custom:
    OpenaiTypesChatChatCompletionMessageCustomToolCallParamCustom$inboundSchema,
  type: z.literal("custom"),
});
/** @internal */
export type ChatCompletionMessageCustomToolCallParam$Outbound = {
  id: string;
  custom:
    OpenaiTypesChatChatCompletionMessageCustomToolCallParamCustom$Outbound;
  type: "custom";
};

/** @internal */
export const ChatCompletionMessageCustomToolCallParam$outboundSchema: z.ZodType<
  ChatCompletionMessageCustomToolCallParam$Outbound,
  z.ZodTypeDef,
  ChatCompletionMessageCustomToolCallParam
> = z.object({
  id: z.string(),
  custom:
    OpenaiTypesChatChatCompletionMessageCustomToolCallParamCustom$outboundSchema,
  type: z.literal("custom"),
});

export function chatCompletionMessageCustomToolCallParamToJSON(
  chatCompletionMessageCustomToolCallParam:
    ChatCompletionMessageCustomToolCallParam,
): string {
  return JSON.stringify(
    ChatCompletionMessageCustomToolCallParam$outboundSchema.parse(
      chatCompletionMessageCustomToolCallParam,
    ),
  );
}
export function chatCompletionMessageCustomToolCallParamFromJSON(
  jsonString: string,
): SafeParseResult<
  ChatCompletionMessageCustomToolCallParam,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ChatCompletionMessageCustomToolCallParam$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ChatCompletionMessageCustomToolCallParam' from JSON`,
  );
}
