/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ChatCompletionFunctionMessageParam = {
  content: string | null;
  name: string;
  role?: "function" | undefined;
};

/** @internal */
export const ChatCompletionFunctionMessageParam$inboundSchema: z.ZodType<
  ChatCompletionFunctionMessageParam,
  z.ZodTypeDef,
  unknown
> = z.object({
  content: z.nullable(z.string()),
  name: z.string(),
  role: z.literal("function").default("function").optional(),
});
/** @internal */
export type ChatCompletionFunctionMessageParam$Outbound = {
  content: string | null;
  name: string;
  role: "function";
};

/** @internal */
export const ChatCompletionFunctionMessageParam$outboundSchema: z.ZodType<
  ChatCompletionFunctionMessageParam$Outbound,
  z.ZodTypeDef,
  ChatCompletionFunctionMessageParam
> = z.object({
  content: z.nullable(z.string()),
  name: z.string(),
  role: z.literal("function"),
});

export function chatCompletionFunctionMessageParamToJSON(
  chatCompletionFunctionMessageParam: ChatCompletionFunctionMessageParam,
): string {
  return JSON.stringify(
    ChatCompletionFunctionMessageParam$outboundSchema.parse(
      chatCompletionFunctionMessageParam,
    ),
  );
}
export function chatCompletionFunctionMessageParamFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionFunctionMessageParam, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ChatCompletionFunctionMessageParam$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionFunctionMessageParam' from JSON`,
  );
}
