/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  OpenaiTypesChatChatCompletionCustomToolParamCustom,
  OpenaiTypesChatChatCompletionCustomToolParamCustom$inboundSchema,
  OpenaiTypesChatChatCompletionCustomToolParamCustom$Outbound,
  OpenaiTypesChatChatCompletionCustomToolParamCustom$outboundSchema,
} from "./openaitypeschatchatcompletioncustomtoolparamcustom.js";

export type ChatCompletionCustomToolParam = {
  custom: OpenaiTypesChatChatCompletionCustomToolParamCustom;
  type?: "custom" | undefined;
};

/** @internal */
export const ChatCompletionCustomToolParam$inboundSchema: z.ZodType<
  ChatCompletionCustomToolParam,
  z.ZodTypeDef,
  unknown
> = z.object({
  custom: OpenaiTypesChatChatCompletionCustomToolParamCustom$inboundSchema,
  type: z.literal("custom").default("custom").optional(),
});
/** @internal */
export type ChatCompletionCustomToolParam$Outbound = {
  custom: OpenaiTypesChatChatCompletionCustomToolParamCustom$Outbound;
  type: "custom";
};

/** @internal */
export const ChatCompletionCustomToolParam$outboundSchema: z.ZodType<
  ChatCompletionCustomToolParam$Outbound,
  z.ZodTypeDef,
  ChatCompletionCustomToolParam
> = z.object({
  custom: OpenaiTypesChatChatCompletionCustomToolParamCustom$outboundSchema,
  type: z.literal("custom"),
});

export function chatCompletionCustomToolParamToJSON(
  chatCompletionCustomToolParam: ChatCompletionCustomToolParam,
): string {
  return JSON.stringify(
    ChatCompletionCustomToolParam$outboundSchema.parse(
      chatCompletionCustomToolParam,
    ),
  );
}
export function chatCompletionCustomToolParamFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionCustomToolParam, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatCompletionCustomToolParam$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionCustomToolParam' from JSON`,
  );
}
