/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ChatCompletionContentPartTextParam,
  ChatCompletionContentPartTextParam$inboundSchema,
  ChatCompletionContentPartTextParam$Outbound,
  ChatCompletionContentPartTextParam$outboundSchema,
} from "./chatcompletioncontentparttextparam.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ChatCompletionPredictionContentParamContent =
  | string
  | Array<ChatCompletionContentPartTextParam>;

export type ChatCompletionPredictionContentParam = {
  content: string | Array<ChatCompletionContentPartTextParam>;
  type: "content";
};

/** @internal */
export const ChatCompletionPredictionContentParamContent$inboundSchema:
  z.ZodType<
    ChatCompletionPredictionContentParamContent,
    z.ZodTypeDef,
    unknown
  > = z.union([
    z.string(),
    z.array(ChatCompletionContentPartTextParam$inboundSchema),
  ]);
/** @internal */
export type ChatCompletionPredictionContentParamContent$Outbound =
  | string
  | Array<ChatCompletionContentPartTextParam$Outbound>;

/** @internal */
export const ChatCompletionPredictionContentParamContent$outboundSchema:
  z.ZodType<
    ChatCompletionPredictionContentParamContent$Outbound,
    z.ZodTypeDef,
    ChatCompletionPredictionContentParamContent
  > = z.union([
    z.string(),
    z.array(ChatCompletionContentPartTextParam$outboundSchema),
  ]);

export function chatCompletionPredictionContentParamContentToJSON(
  chatCompletionPredictionContentParamContent:
    ChatCompletionPredictionContentParamContent,
): string {
  return JSON.stringify(
    ChatCompletionPredictionContentParamContent$outboundSchema.parse(
      chatCompletionPredictionContentParamContent,
    ),
  );
}
export function chatCompletionPredictionContentParamContentFromJSON(
  jsonString: string,
): SafeParseResult<
  ChatCompletionPredictionContentParamContent,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ChatCompletionPredictionContentParamContent$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ChatCompletionPredictionContentParamContent' from JSON`,
  );
}

/** @internal */
export const ChatCompletionPredictionContentParam$inboundSchema: z.ZodType<
  ChatCompletionPredictionContentParam,
  z.ZodTypeDef,
  unknown
> = z.object({
  content: z.union([
    z.string(),
    z.array(ChatCompletionContentPartTextParam$inboundSchema),
  ]),
  type: z.literal("content"),
});
/** @internal */
export type ChatCompletionPredictionContentParam$Outbound = {
  content: string | Array<ChatCompletionContentPartTextParam$Outbound>;
  type: "content";
};

/** @internal */
export const ChatCompletionPredictionContentParam$outboundSchema: z.ZodType<
  ChatCompletionPredictionContentParam$Outbound,
  z.ZodTypeDef,
  ChatCompletionPredictionContentParam
> = z.object({
  content: z.union([
    z.string(),
    z.array(ChatCompletionContentPartTextParam$outboundSchema),
  ]),
  type: z.literal("content"),
});

export function chatCompletionPredictionContentParamToJSON(
  chatCompletionPredictionContentParam: ChatCompletionPredictionContentParam,
): string {
  return JSON.stringify(
    ChatCompletionPredictionContentParam$outboundSchema.parse(
      chatCompletionPredictionContentParam,
    ),
  );
}
export function chatCompletionPredictionContentParamFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionPredictionContentParam, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ChatCompletionPredictionContentParam$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionPredictionContentParam' from JSON`,
  );
}
