/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  CustomOutput,
  CustomOutput$inboundSchema,
  CustomOutput$Outbound,
  CustomOutput$outboundSchema,
} from "./customoutput.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ChatCompletionMessageCustomToolCall = {
  id: string;
  custom: CustomOutput;
  type: "custom";
  additionalProperties?: { [k: string]: any } | undefined;
};

/** @internal */
export const ChatCompletionMessageCustomToolCall$inboundSchema: z.ZodType<
  ChatCompletionMessageCustomToolCall,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    id: z.string(),
    custom: CustomOutput$inboundSchema,
    type: z.literal("custom"),
  }).catchall(z.any()),
  "additionalProperties",
  true,
);
/** @internal */
export type ChatCompletionMessageCustomToolCall$Outbound = {
  id: string;
  custom: CustomOutput$Outbound;
  type: "custom";
  [additionalProperties: string]: unknown;
};

/** @internal */
export const ChatCompletionMessageCustomToolCall$outboundSchema: z.ZodType<
  ChatCompletionMessageCustomToolCall$Outbound,
  z.ZodTypeDef,
  ChatCompletionMessageCustomToolCall
> = z.object({
  id: z.string(),
  custom: CustomOutput$outboundSchema,
  type: z.literal("custom"),
  additionalProperties: z.record(z.any()).optional(),
}).transform((v) => {
  return {
    ...v.additionalProperties,
    ...remap$(v, {
      additionalProperties: null,
    }),
  };
});

export function chatCompletionMessageCustomToolCallToJSON(
  chatCompletionMessageCustomToolCall: ChatCompletionMessageCustomToolCall,
): string {
  return JSON.stringify(
    ChatCompletionMessageCustomToolCall$outboundSchema.parse(
      chatCompletionMessageCustomToolCall,
    ),
  );
}
export function chatCompletionMessageCustomToolCallFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionMessageCustomToolCall, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ChatCompletionMessageCustomToolCall$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionMessageCustomToolCall' from JSON`,
  );
}
