/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  Annotation,
  Annotation$inboundSchema,
  Annotation$Outbound,
  Annotation$outboundSchema,
} from "./annotation.js";
import {
  ChatCompletionAudio,
  ChatCompletionAudio$inboundSchema,
  ChatCompletionAudio$Outbound,
  ChatCompletionAudio$outboundSchema,
} from "./chatcompletionaudio.js";
import {
  ChatCompletionMessageCustomToolCallOutput,
  ChatCompletionMessageCustomToolCallOutput$inboundSchema,
  ChatCompletionMessageCustomToolCallOutput$Outbound,
  ChatCompletionMessageCustomToolCallOutput$outboundSchema,
} from "./chatcompletionmessagecustomtoolcalloutput.js";
import {
  ChatCompletionMessageFunctionToolCallOutput,
  ChatCompletionMessageFunctionToolCallOutput$inboundSchema,
  ChatCompletionMessageFunctionToolCallOutput$Outbound,
  ChatCompletionMessageFunctionToolCallOutput$outboundSchema,
} from "./chatcompletionmessagefunctiontoolcalloutput.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  FunctionCallOutput,
  FunctionCallOutput$inboundSchema,
  FunctionCallOutput$Outbound,
  FunctionCallOutput$outboundSchema,
} from "./functioncalloutput.js";

export type ChatCompletionMessageOutputToolCall =
  | ChatCompletionMessageFunctionToolCallOutput
  | ChatCompletionMessageCustomToolCallOutput;

export type ChatCompletionMessageOutput = {
  content?: string | null | undefined;
  refusal?: string | null | undefined;
  role?: "assistant" | undefined;
  annotations?: Array<Annotation> | null | undefined;
  audio?: ChatCompletionAudio | null | undefined;
  functionCall?: FunctionCallOutput | null | undefined;
  toolCalls?:
    | Array<
      | ChatCompletionMessageFunctionToolCallOutput
      | ChatCompletionMessageCustomToolCallOutput
    >
    | null
    | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

/** @internal */
export const ChatCompletionMessageOutputToolCall$inboundSchema: z.ZodType<
  ChatCompletionMessageOutputToolCall,
  z.ZodTypeDef,
  unknown
> = z.union([
  ChatCompletionMessageFunctionToolCallOutput$inboundSchema,
  ChatCompletionMessageCustomToolCallOutput$inboundSchema,
]);

/** @internal */
export type ChatCompletionMessageOutputToolCall$Outbound =
  | ChatCompletionMessageFunctionToolCallOutput$Outbound
  | ChatCompletionMessageCustomToolCallOutput$Outbound;

/** @internal */
export const ChatCompletionMessageOutputToolCall$outboundSchema: z.ZodType<
  ChatCompletionMessageOutputToolCall$Outbound,
  z.ZodTypeDef,
  ChatCompletionMessageOutputToolCall
> = z.union([
  ChatCompletionMessageFunctionToolCallOutput$outboundSchema,
  ChatCompletionMessageCustomToolCallOutput$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChatCompletionMessageOutputToolCall$ {
  /** @deprecated use `ChatCompletionMessageOutputToolCall$inboundSchema` instead. */
  export const inboundSchema =
    ChatCompletionMessageOutputToolCall$inboundSchema;
  /** @deprecated use `ChatCompletionMessageOutputToolCall$outboundSchema` instead. */
  export const outboundSchema =
    ChatCompletionMessageOutputToolCall$outboundSchema;
  /** @deprecated use `ChatCompletionMessageOutputToolCall$Outbound` instead. */
  export type Outbound = ChatCompletionMessageOutputToolCall$Outbound;
}

export function chatCompletionMessageOutputToolCallToJSON(
  chatCompletionMessageOutputToolCall: ChatCompletionMessageOutputToolCall,
): string {
  return JSON.stringify(
    ChatCompletionMessageOutputToolCall$outboundSchema.parse(
      chatCompletionMessageOutputToolCall,
    ),
  );
}

export function chatCompletionMessageOutputToolCallFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionMessageOutputToolCall, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ChatCompletionMessageOutputToolCall$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionMessageOutputToolCall' from JSON`,
  );
}

/** @internal */
export const ChatCompletionMessageOutput$inboundSchema: z.ZodType<
  ChatCompletionMessageOutput,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    content: z.nullable(z.string()).optional(),
    refusal: z.nullable(z.string()).optional(),
    role: z.literal("assistant").default("assistant").optional(),
    annotations: z.nullable(z.array(Annotation$inboundSchema)).optional(),
    audio: z.nullable(ChatCompletionAudio$inboundSchema).optional(),
    function_call: z.nullable(FunctionCallOutput$inboundSchema).optional(),
    tool_calls: z.nullable(
      z.array(
        z.union([
          ChatCompletionMessageFunctionToolCallOutput$inboundSchema,
          ChatCompletionMessageCustomToolCallOutput$inboundSchema,
        ]),
      ),
    ).optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
).transform((v) => {
  return remap$(v, {
    "function_call": "functionCall",
    "tool_calls": "toolCalls",
  });
});

/** @internal */
export type ChatCompletionMessageOutput$Outbound = {
  content?: string | null | undefined;
  refusal?: string | null | undefined;
  role: "assistant";
  annotations?: Array<Annotation$Outbound> | null | undefined;
  audio?: ChatCompletionAudio$Outbound | null | undefined;
  function_call?: FunctionCallOutput$Outbound | null | undefined;
  tool_calls?:
    | Array<
      | ChatCompletionMessageFunctionToolCallOutput$Outbound
      | ChatCompletionMessageCustomToolCallOutput$Outbound
    >
    | null
    | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const ChatCompletionMessageOutput$outboundSchema: z.ZodType<
  ChatCompletionMessageOutput$Outbound,
  z.ZodTypeDef,
  ChatCompletionMessageOutput
> = z.object({
  content: z.nullable(z.string()).optional(),
  refusal: z.nullable(z.string()).optional(),
  role: z.literal("assistant"),
  annotations: z.nullable(z.array(Annotation$outboundSchema)).optional(),
  audio: z.nullable(ChatCompletionAudio$outboundSchema).optional(),
  functionCall: z.nullable(FunctionCallOutput$outboundSchema).optional(),
  toolCalls: z.nullable(
    z.array(
      z.union([
        ChatCompletionMessageFunctionToolCallOutput$outboundSchema,
        ChatCompletionMessageCustomToolCallOutput$outboundSchema,
      ]),
    ),
  ).optional(),
  additionalProperties: z.record(z.any()).optional(),
}).transform((v) => {
  return {
    ...v.additionalProperties,
    ...remap$(v, {
      functionCall: "function_call",
      toolCalls: "tool_calls",
      additionalProperties: null,
    }),
  };
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChatCompletionMessageOutput$ {
  /** @deprecated use `ChatCompletionMessageOutput$inboundSchema` instead. */
  export const inboundSchema = ChatCompletionMessageOutput$inboundSchema;
  /** @deprecated use `ChatCompletionMessageOutput$outboundSchema` instead. */
  export const outboundSchema = ChatCompletionMessageOutput$outboundSchema;
  /** @deprecated use `ChatCompletionMessageOutput$Outbound` instead. */
  export type Outbound = ChatCompletionMessageOutput$Outbound;
}

export function chatCompletionMessageOutputToJSON(
  chatCompletionMessageOutput: ChatCompletionMessageOutput,
): string {
  return JSON.stringify(
    ChatCompletionMessageOutput$outboundSchema.parse(
      chatCompletionMessageOutput,
    ),
  );
}

export function chatCompletionMessageOutputFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionMessageOutput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatCompletionMessageOutput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionMessageOutput' from JSON`,
  );
}
