/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  TopLogprob,
  TopLogprob$inboundSchema,
  TopLogprob$Outbound,
  TopLogprob$outboundSchema,
} from "./toplogprob.js";

export type ChatCompletionTokenLogprob = {
  token: string;
  bytes?: Array<number> | null | undefined;
  logprob: number;
  topLogprobs: Array<TopLogprob>;
  additionalProperties?: { [k: string]: any } | undefined;
};

/** @internal */
export const ChatCompletionTokenLogprob$inboundSchema: z.ZodType<
  ChatCompletionTokenLogprob,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    token: z.string(),
    bytes: z.nullable(z.array(z.number().int())).optional(),
    logprob: z.number(),
    top_logprobs: z.array(TopLogprob$inboundSchema),
  }).catchall(z.any()),
  "additionalProperties",
  true,
).transform((v) => {
  return remap$(v, {
    "top_logprobs": "topLogprobs",
  });
});

/** @internal */
export type ChatCompletionTokenLogprob$Outbound = {
  token: string;
  bytes?: Array<number> | null | undefined;
  logprob: number;
  top_logprobs: Array<TopLogprob$Outbound>;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const ChatCompletionTokenLogprob$outboundSchema: z.ZodType<
  ChatCompletionTokenLogprob$Outbound,
  z.ZodTypeDef,
  ChatCompletionTokenLogprob
> = z.object({
  token: z.string(),
  bytes: z.nullable(z.array(z.number().int())).optional(),
  logprob: z.number(),
  topLogprobs: z.array(TopLogprob$outboundSchema),
  additionalProperties: z.record(z.any()).optional(),
}).transform((v) => {
  return {
    ...v.additionalProperties,
    ...remap$(v, {
      topLogprobs: "top_logprobs",
      additionalProperties: null,
    }),
  };
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChatCompletionTokenLogprob$ {
  /** @deprecated use `ChatCompletionTokenLogprob$inboundSchema` instead. */
  export const inboundSchema = ChatCompletionTokenLogprob$inboundSchema;
  /** @deprecated use `ChatCompletionTokenLogprob$outboundSchema` instead. */
  export const outboundSchema = ChatCompletionTokenLogprob$outboundSchema;
  /** @deprecated use `ChatCompletionTokenLogprob$Outbound` instead. */
  export type Outbound = ChatCompletionTokenLogprob$Outbound;
}

export function chatCompletionTokenLogprobToJSON(
  chatCompletionTokenLogprob: ChatCompletionTokenLogprob,
): string {
  return JSON.stringify(
    ChatCompletionTokenLogprob$outboundSchema.parse(chatCompletionTokenLogprob),
  );
}

export function chatCompletionTokenLogprobFromJSON(
  jsonString: string,
): SafeParseResult<ChatCompletionTokenLogprob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatCompletionTokenLogprob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCompletionTokenLogprob' from JSON`,
  );
}
