/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ChatCompletionTokenLogprob,
  ChatCompletionTokenLogprob$inboundSchema,
  ChatCompletionTokenLogprob$Outbound,
  ChatCompletionTokenLogprob$outboundSchema,
} from "./chatcompletiontokenlogprob.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ChoiceLogprobsOutput = {
  content?: Array<ChatCompletionTokenLogprob> | null | undefined;
  refusal?: Array<ChatCompletionTokenLogprob> | null | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

/** @internal */
export const ChoiceLogprobsOutput$inboundSchema: z.ZodType<
  ChoiceLogprobsOutput,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    content: z.nullable(z.array(ChatCompletionTokenLogprob$inboundSchema))
      .optional(),
    refusal: z.nullable(z.array(ChatCompletionTokenLogprob$inboundSchema))
      .optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
);

/** @internal */
export type ChoiceLogprobsOutput$Outbound = {
  content?: Array<ChatCompletionTokenLogprob$Outbound> | null | undefined;
  refusal?: Array<ChatCompletionTokenLogprob$Outbound> | null | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const ChoiceLogprobsOutput$outboundSchema: z.ZodType<
  ChoiceLogprobsOutput$Outbound,
  z.ZodTypeDef,
  ChoiceLogprobsOutput
> = z.object({
  content: z.nullable(z.array(ChatCompletionTokenLogprob$outboundSchema))
    .optional(),
  refusal: z.nullable(z.array(ChatCompletionTokenLogprob$outboundSchema))
    .optional(),
  additionalProperties: z.record(z.any()).optional(),
}).transform((v) => {
  return {
    ...v.additionalProperties,
    ...remap$(v, {
      additionalProperties: null,
    }),
  };
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChoiceLogprobsOutput$ {
  /** @deprecated use `ChoiceLogprobsOutput$inboundSchema` instead. */
  export const inboundSchema = ChoiceLogprobsOutput$inboundSchema;
  /** @deprecated use `ChoiceLogprobsOutput$outboundSchema` instead. */
  export const outboundSchema = ChoiceLogprobsOutput$outboundSchema;
  /** @deprecated use `ChoiceLogprobsOutput$Outbound` instead. */
  export type Outbound = ChoiceLogprobsOutput$Outbound;
}

export function choiceLogprobsOutputToJSON(
  choiceLogprobsOutput: ChoiceLogprobsOutput,
): string {
  return JSON.stringify(
    ChoiceLogprobsOutput$outboundSchema.parse(choiceLogprobsOutput),
  );
}

export function choiceLogprobsOutputFromJSON(
  jsonString: string,
): SafeParseResult<ChoiceLogprobsOutput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChoiceLogprobsOutput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChoiceLogprobsOutput' from JSON`,
  );
}
