/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  CompletionTokensDetails,
  CompletionTokensDetails$inboundSchema,
  CompletionTokensDetails$Outbound,
  CompletionTokensDetails$outboundSchema,
} from "./completiontokensdetails.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  PromptTokensDetails,
  PromptTokensDetails$inboundSchema,
  PromptTokensDetails$Outbound,
  PromptTokensDetails$outboundSchema,
} from "./prompttokensdetails.js";

export type CompletionUsage = {
  completionTokens: number;
  promptTokens: number;
  totalTokens: number;
  completionTokensDetails?: CompletionTokensDetails | null | undefined;
  promptTokensDetails?: PromptTokensDetails | null | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

/** @internal */
export const CompletionUsage$inboundSchema: z.ZodType<
  CompletionUsage,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    completion_tokens: z.number().int(),
    prompt_tokens: z.number().int(),
    total_tokens: z.number().int(),
    completion_tokens_details: z.nullable(CompletionTokensDetails$inboundSchema)
      .optional(),
    prompt_tokens_details: z.nullable(PromptTokensDetails$inboundSchema)
      .optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
).transform((v) => {
  return remap$(v, {
    "completion_tokens": "completionTokens",
    "prompt_tokens": "promptTokens",
    "total_tokens": "totalTokens",
    "completion_tokens_details": "completionTokensDetails",
    "prompt_tokens_details": "promptTokensDetails",
  });
});

/** @internal */
export type CompletionUsage$Outbound = {
  completion_tokens: number;
  prompt_tokens: number;
  total_tokens: number;
  completion_tokens_details?:
    | CompletionTokensDetails$Outbound
    | null
    | undefined;
  prompt_tokens_details?: PromptTokensDetails$Outbound | null | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const CompletionUsage$outboundSchema: z.ZodType<
  CompletionUsage$Outbound,
  z.ZodTypeDef,
  CompletionUsage
> = z.object({
  completionTokens: z.number().int(),
  promptTokens: z.number().int(),
  totalTokens: z.number().int(),
  completionTokensDetails: z.nullable(CompletionTokensDetails$outboundSchema)
    .optional(),
  promptTokensDetails: z.nullable(PromptTokensDetails$outboundSchema)
    .optional(),
  additionalProperties: z.record(z.any()).optional(),
}).transform((v) => {
  return {
    ...v.additionalProperties,
    ...remap$(v, {
      completionTokens: "completion_tokens",
      promptTokens: "prompt_tokens",
      totalTokens: "total_tokens",
      completionTokensDetails: "completion_tokens_details",
      promptTokensDetails: "prompt_tokens_details",
      additionalProperties: null,
    }),
  };
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CompletionUsage$ {
  /** @deprecated use `CompletionUsage$inboundSchema` instead. */
  export const inboundSchema = CompletionUsage$inboundSchema;
  /** @deprecated use `CompletionUsage$outboundSchema` instead. */
  export const outboundSchema = CompletionUsage$outboundSchema;
  /** @deprecated use `CompletionUsage$Outbound` instead. */
  export type Outbound = CompletionUsage$Outbound;
}

export function completionUsageToJSON(
  completionUsage: CompletionUsage,
): string {
  return JSON.stringify(CompletionUsage$outboundSchema.parse(completionUsage));
}

export function completionUsageFromJSON(
  jsonString: string,
): SafeParseResult<CompletionUsage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CompletionUsage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CompletionUsage' from JSON`,
  );
}
