/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CreateModelAliasResponse = {
  /**
   * The ID of the model alias
   */
  id: string;
  /**
   * The name of the model alias
   */
  name: string;
  /**
   * Ordered list of model names to try as fallbacks
   */
  fallbackModels: Array<string>;
  /**
   * Optional description of the model alias
   */
  description?: string | null | undefined;
};

/** @internal */
export const CreateModelAliasResponse$inboundSchema: z.ZodType<
  CreateModelAliasResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  fallback_models: z.array(z.string()),
  description: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "fallback_models": "fallbackModels",
  });
});
/** @internal */
export type CreateModelAliasResponse$Outbound = {
  id: string;
  name: string;
  fallback_models: Array<string>;
  description?: string | null | undefined;
};

/** @internal */
export const CreateModelAliasResponse$outboundSchema: z.ZodType<
  CreateModelAliasResponse$Outbound,
  z.ZodTypeDef,
  CreateModelAliasResponse
> = z.object({
  id: z.string(),
  name: z.string(),
  fallbackModels: z.array(z.string()),
  description: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    fallbackModels: "fallback_models",
  });
});

export function createModelAliasResponseToJSON(
  createModelAliasResponse: CreateModelAliasResponse,
): string {
  return JSON.stringify(
    CreateModelAliasResponse$outboundSchema.parse(createModelAliasResponse),
  );
}
export function createModelAliasResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateModelAliasResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateModelAliasResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateModelAliasResponse' from JSON`,
  );
}
