/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const Syntax = {
  Lark: "lark",
  Regex: "regex",
} as const;
export type Syntax = ClosedEnum<typeof Syntax>;

export type CustomFormatGrammarGrammar = {
  definition: string;
  syntax: Syntax;
};

/** @internal */
export const Syntax$inboundSchema: z.ZodNativeEnum<typeof Syntax> = z
  .nativeEnum(Syntax);
/** @internal */
export const Syntax$outboundSchema: z.ZodNativeEnum<typeof Syntax> =
  Syntax$inboundSchema;

/** @internal */
export const CustomFormatGrammarGrammar$inboundSchema: z.ZodType<
  CustomFormatGrammarGrammar,
  z.ZodTypeDef,
  unknown
> = z.object({
  definition: z.string(),
  syntax: Syntax$inboundSchema,
});
/** @internal */
export type CustomFormatGrammarGrammar$Outbound = {
  definition: string;
  syntax: string;
};

/** @internal */
export const CustomFormatGrammarGrammar$outboundSchema: z.ZodType<
  CustomFormatGrammarGrammar$Outbound,
  z.ZodTypeDef,
  CustomFormatGrammarGrammar
> = z.object({
  definition: z.string(),
  syntax: Syntax$outboundSchema,
});

export function customFormatGrammarGrammarToJSON(
  customFormatGrammarGrammar: CustomFormatGrammarGrammar,
): string {
  return JSON.stringify(
    CustomFormatGrammarGrammar$outboundSchema.parse(customFormatGrammarGrammar),
  );
}
export function customFormatGrammarGrammarFromJSON(
  jsonString: string,
): SafeParseResult<CustomFormatGrammarGrammar, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomFormatGrammarGrammar$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomFormatGrammarGrammar' from JSON`,
  );
}
