/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const ScorersEnum2 = {
  Base: "base",
  Rubrics: "rubrics",
  Toxicity: "toxicity",
  Hallucination: "hallucination",
  Qa: "qa",
  AgentToolSelection: "agent_tool_selection",
  Regex: "regex",
  MaxLength: "max_length",
} as const;
export type ScorersEnum2 = ClosedEnum<typeof ScorersEnum2>;

export type ScorersUnion1 = ScorersEnum2 | { [k: string]: any };

export const ScorersEnum1 = {
  Base: "base",
  Rubrics: "rubrics",
  Toxicity: "toxicity",
  Hallucination: "hallucination",
  Qa: "qa",
  AgentToolSelection: "agent_tool_selection",
  Regex: "regex",
  MaxLength: "max_length",
} as const;
export type ScorersEnum1 = ClosedEnum<typeof ScorersEnum1>;

/**
 * Evaluation scorers to run: 'base', 'rubrics', 'toxicity', 'hallucination', 'qa', 'agent_tool_selection', 'regex', 'max_length', or a list of them.
 */
export type ScorersUnion2 =
  | ScorersEnum1
  | { [k: string]: any }
  | Array<ScorersEnum2 | { [k: string]: any }>;

/**
 * Configuration for evaluation features stored under 'beta.evaluation'.
 *
 * @remarks
 *
 * - enabled: master switch
 * - scorers: which evaluators to run. Accepts:
 *     - string: "base" | "rubrics" | "toxicity" | "hallucination" | "qa"
 *     - dict: { "rubrics": RubricDefinition-like payload }
 *     - list[str | dict]
 *   "base" is the default scorer.
 */
export type EvaluationConfig = {
  /**
   * Enable evaluation features (base or rubrics).
   */
  enabled?: boolean | undefined;
  /**
   * Evaluation scorers to run: 'base', 'rubrics', 'toxicity', 'hallucination', 'qa', 'agent_tool_selection', 'regex', 'max_length', or a list of them.
   */
  scorers?:
    | ScorersEnum1
    | { [k: string]: any }
    | Array<ScorersEnum2 | { [k: string]: any }>
    | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

/** @internal */
export const ScorersEnum2$inboundSchema: z.ZodNativeEnum<typeof ScorersEnum2> =
  z.nativeEnum(ScorersEnum2);
/** @internal */
export const ScorersEnum2$outboundSchema: z.ZodNativeEnum<typeof ScorersEnum2> =
  ScorersEnum2$inboundSchema;

/** @internal */
export const ScorersUnion1$inboundSchema: z.ZodType<
  ScorersUnion1,
  z.ZodTypeDef,
  unknown
> = z.union([ScorersEnum2$inboundSchema, z.record(z.any())]);
/** @internal */
export type ScorersUnion1$Outbound = string | { [k: string]: any };

/** @internal */
export const ScorersUnion1$outboundSchema: z.ZodType<
  ScorersUnion1$Outbound,
  z.ZodTypeDef,
  ScorersUnion1
> = z.union([ScorersEnum2$outboundSchema, z.record(z.any())]);

export function scorersUnion1ToJSON(scorersUnion1: ScorersUnion1): string {
  return JSON.stringify(ScorersUnion1$outboundSchema.parse(scorersUnion1));
}
export function scorersUnion1FromJSON(
  jsonString: string,
): SafeParseResult<ScorersUnion1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScorersUnion1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScorersUnion1' from JSON`,
  );
}

/** @internal */
export const ScorersEnum1$inboundSchema: z.ZodNativeEnum<typeof ScorersEnum1> =
  z.nativeEnum(ScorersEnum1);
/** @internal */
export const ScorersEnum1$outboundSchema: z.ZodNativeEnum<typeof ScorersEnum1> =
  ScorersEnum1$inboundSchema;

/** @internal */
export const ScorersUnion2$inboundSchema: z.ZodType<
  ScorersUnion2,
  z.ZodTypeDef,
  unknown
> = z.union([
  ScorersEnum1$inboundSchema,
  z.record(z.any()),
  z.array(z.union([ScorersEnum2$inboundSchema, z.record(z.any())])),
]);
/** @internal */
export type ScorersUnion2$Outbound =
  | string
  | { [k: string]: any }
  | Array<string | { [k: string]: any }>;

/** @internal */
export const ScorersUnion2$outboundSchema: z.ZodType<
  ScorersUnion2$Outbound,
  z.ZodTypeDef,
  ScorersUnion2
> = z.union([
  ScorersEnum1$outboundSchema,
  z.record(z.any()),
  z.array(z.union([ScorersEnum2$outboundSchema, z.record(z.any())])),
]);

export function scorersUnion2ToJSON(scorersUnion2: ScorersUnion2): string {
  return JSON.stringify(ScorersUnion2$outboundSchema.parse(scorersUnion2));
}
export function scorersUnion2FromJSON(
  jsonString: string,
): SafeParseResult<ScorersUnion2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScorersUnion2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScorersUnion2' from JSON`,
  );
}

/** @internal */
export const EvaluationConfig$inboundSchema: z.ZodType<
  EvaluationConfig,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    enabled: z.boolean().default(true),
    scorers: z.union([
      ScorersEnum1$inboundSchema,
      z.record(z.any()),
      z.array(z.union([ScorersEnum2$inboundSchema, z.record(z.any())])),
    ]).optional(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
);
/** @internal */
export type EvaluationConfig$Outbound = {
  enabled: boolean;
  scorers?:
    | string
    | { [k: string]: any }
    | Array<string | { [k: string]: any }>
    | undefined;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const EvaluationConfig$outboundSchema: z.ZodType<
  EvaluationConfig$Outbound,
  z.ZodTypeDef,
  EvaluationConfig
> = z.object({
  enabled: z.boolean().default(true),
  scorers: z.union([
    ScorersEnum1$outboundSchema,
    z.record(z.any()),
    z.array(z.union([ScorersEnum2$outboundSchema, z.record(z.any())])),
  ]).optional(),
  additionalProperties: z.record(z.any()).optional(),
}).transform((v) => {
  return {
    ...v.additionalProperties,
    ...remap$(v, {
      additionalProperties: null,
    }),
  };
});

export function evaluationConfigToJSON(
  evaluationConfig: EvaluationConfig,
): string {
  return JSON.stringify(
    EvaluationConfig$outboundSchema.parse(evaluationConfig),
  );
}
export function evaluationConfigFromJSON(
  jsonString: string,
): SafeParseResult<EvaluationConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EvaluationConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EvaluationConfig' from JSON`,
  );
}
