/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type FileDownloadUrlResponse = {
  /**
   * Presigned URL to download the file
   */
  url: string;
  /**
   * Number of seconds until the URL expires
   */
  expiresIn: number;
};

/** @internal */
export const FileDownloadUrlResponse$inboundSchema: z.ZodType<
  FileDownloadUrlResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  url: z.string(),
  expires_in: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "expires_in": "expiresIn",
  });
});
/** @internal */
export type FileDownloadUrlResponse$Outbound = {
  url: string;
  expires_in: number;
};

/** @internal */
export const FileDownloadUrlResponse$outboundSchema: z.ZodType<
  FileDownloadUrlResponse$Outbound,
  z.ZodTypeDef,
  FileDownloadUrlResponse
> = z.object({
  url: z.string(),
  expiresIn: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    expiresIn: "expires_in",
  });
});

export function fileDownloadUrlResponseToJSON(
  fileDownloadUrlResponse: FileDownloadUrlResponse,
): string {
  return JSON.stringify(
    FileDownloadUrlResponse$outboundSchema.parse(fileDownloadUrlResponse),
  );
}
export function fileDownloadUrlResponseFromJSON(
  jsonString: string,
): SafeParseResult<FileDownloadUrlResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FileDownloadUrlResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FileDownloadUrlResponse' from JSON`,
  );
}
