/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Deprecated and replaced by `tool_calls`.
 *
 * @remarks
 *
 * The name and arguments of a function that should be called, as generated by the model.
 */
export type FunctionCallInput = {
  arguments: string;
  name: string;
};

/** @internal */
export const FunctionCallInput$inboundSchema: z.ZodType<
  FunctionCallInput,
  z.ZodTypeDef,
  unknown
> = z.object({
  arguments: z.string(),
  name: z.string(),
});
/** @internal */
export type FunctionCallInput$Outbound = {
  arguments: string;
  name: string;
};

/** @internal */
export const FunctionCallInput$outboundSchema: z.ZodType<
  FunctionCallInput$Outbound,
  z.ZodTypeDef,
  FunctionCallInput
> = z.object({
  arguments: z.string(),
  name: z.string(),
});

export function functionCallInputToJSON(
  functionCallInput: FunctionCallInput,
): string {
  return JSON.stringify(
    FunctionCallInput$outboundSchema.parse(functionCallInput),
  );
}
export function functionCallInputFromJSON(
  jsonString: string,
): SafeParseResult<FunctionCallInput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FunctionCallInput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FunctionCallInput' from JSON`,
  );
}
