/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type GetDatasetEntryResponse = {
  /**
   * The id of the dataset entry
   */
  id: string;
  /**
   * The input to the dataset entry
   */
  input: string;
  /**
   * The output to the dataset entry
   */
  output: string;
  /**
   * The expected output to the dataset entry, this is an optionally edited version of the output
   */
  expected?: string | null | undefined;
  /**
   * The comment to the dataset entry
   */
  comment?: string | null | undefined;
};

/** @internal */
export const GetDatasetEntryResponse$inboundSchema: z.ZodType<
  GetDatasetEntryResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  input: z.string(),
  output: z.string(),
  expected: z.nullable(z.string()).optional(),
  comment: z.nullable(z.string()).optional(),
});
/** @internal */
export type GetDatasetEntryResponse$Outbound = {
  id: string;
  input: string;
  output: string;
  expected?: string | null | undefined;
  comment?: string | null | undefined;
};

/** @internal */
export const GetDatasetEntryResponse$outboundSchema: z.ZodType<
  GetDatasetEntryResponse$Outbound,
  z.ZodTypeDef,
  GetDatasetEntryResponse
> = z.object({
  id: z.string(),
  input: z.string(),
  output: z.string(),
  expected: z.nullable(z.string()).optional(),
  comment: z.nullable(z.string()).optional(),
});

export function getDatasetEntryResponseToJSON(
  getDatasetEntryResponse: GetDatasetEntryResponse,
): string {
  return JSON.stringify(
    GetDatasetEntryResponse$outboundSchema.parse(getDatasetEntryResponse),
  );
}
export function getDatasetEntryResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetDatasetEntryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDatasetEntryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDatasetEntryResponse' from JSON`,
  );
}
