/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  DocumentSegment,
  DocumentSegment$inboundSchema,
  DocumentSegment$Outbound,
  DocumentSegment$outboundSchema,
} from "./documentsegment.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type GetDocumentResponse = {
  /**
   * The id of the document
   */
  id: string;
  /**
   * The key of the document
   */
  key: string;
  /**
   * The content segments of the document. Documents are split into segments for indexing, and segments may have overlapping text.
   */
  segments: Array<DocumentSegment>;
  /**
   * The metadata of the document
   */
  metadata?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const GetDocumentResponse$inboundSchema: z.ZodType<
  GetDocumentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  key: z.string(),
  segments: z.array(DocumentSegment$inboundSchema),
  metadata: z.nullable(z.record(z.any())).optional(),
});
/** @internal */
export type GetDocumentResponse$Outbound = {
  id: string;
  key: string;
  segments: Array<DocumentSegment$Outbound>;
  metadata?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const GetDocumentResponse$outboundSchema: z.ZodType<
  GetDocumentResponse$Outbound,
  z.ZodTypeDef,
  GetDocumentResponse
> = z.object({
  id: z.string(),
  key: z.string(),
  segments: z.array(DocumentSegment$outboundSchema),
  metadata: z.nullable(z.record(z.any())).optional(),
});

export function getDocumentResponseToJSON(
  getDocumentResponse: GetDocumentResponse,
): string {
  return JSON.stringify(
    GetDocumentResponse$outboundSchema.parse(getDocumentResponse),
  );
}
export function getDocumentResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetDocumentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDocumentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDocumentResponse' from JSON`,
  );
}
