/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type GetUploadUrlResponse = {
  url: string;
  fields: { [k: string]: any };
  id: string;
};

/** @internal */
export const GetUploadUrlResponse$inboundSchema: z.ZodType<
  GetUploadUrlResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  url: z.string(),
  fields: z.record(z.any()),
  id: z.string(),
});
/** @internal */
export type GetUploadUrlResponse$Outbound = {
  url: string;
  fields: { [k: string]: any };
  id: string;
};

/** @internal */
export const GetUploadUrlResponse$outboundSchema: z.ZodType<
  GetUploadUrlResponse$Outbound,
  z.ZodTypeDef,
  GetUploadUrlResponse
> = z.object({
  url: z.string(),
  fields: z.record(z.any()),
  id: z.string(),
});

export function getUploadUrlResponseToJSON(
  getUploadUrlResponse: GetUploadUrlResponse,
): string {
  return JSON.stringify(
    GetUploadUrlResponse$outboundSchema.parse(getUploadUrlResponse),
  );
}
export function getUploadUrlResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetUploadUrlResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUploadUrlResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUploadUrlResponse' from JSON`,
  );
}
