/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type GetUsageResultItemOutput = {
  /**
   * The start time of the time bucket
   */
  timeBucket: Date;
  /**
   * The cost in USD for the time bucket
   */
  cost: string;
  additionalProperties?: { [k: string]: any } | undefined;
};

/** @internal */
export const GetUsageResultItemOutput$inboundSchema: z.ZodType<
  GetUsageResultItemOutput,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    time_bucket: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    cost: z.string(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
).transform((v) => {
  return remap$(v, {
    "time_bucket": "timeBucket",
  });
});

/** @internal */
export type GetUsageResultItemOutput$Outbound = {
  time_bucket: string;
  cost: string;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const GetUsageResultItemOutput$outboundSchema: z.ZodType<
  GetUsageResultItemOutput$Outbound,
  z.ZodTypeDef,
  GetUsageResultItemOutput
> = z.object({
  timeBucket: z.date().transform(v => v.toISOString()),
  cost: z.string(),
  additionalProperties: z.record(z.any()).optional(),
}).transform((v) => {
  return {
    ...v.additionalProperties,
    ...remap$(v, {
      timeBucket: "time_bucket",
      additionalProperties: null,
    }),
  };
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUsageResultItemOutput$ {
  /** @deprecated use `GetUsageResultItemOutput$inboundSchema` instead. */
  export const inboundSchema = GetUsageResultItemOutput$inboundSchema;
  /** @deprecated use `GetUsageResultItemOutput$outboundSchema` instead. */
  export const outboundSchema = GetUsageResultItemOutput$outboundSchema;
  /** @deprecated use `GetUsageResultItemOutput$Outbound` instead. */
  export type Outbound = GetUsageResultItemOutput$Outbound;
}

export function getUsageResultItemOutputToJSON(
  getUsageResultItemOutput: GetUsageResultItemOutput,
): string {
  return JSON.stringify(
    GetUsageResultItemOutput$outboundSchema.parse(getUsageResultItemOutput),
  );
}

export function getUsageResultItemOutputFromJSON(
  jsonString: string,
): SafeParseResult<GetUsageResultItemOutput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUsageResultItemOutput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUsageResultItemOutput' from JSON`,
  );
}
