/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const Granularity = {
  Minute: "minute",
  Hour: "hour",
  Day: "day",
  Month: "month",
  Year: "year",
} as const;
export type Granularity = ClosedEnum<typeof Granularity>;

/** @internal */
export const Granularity$inboundSchema: z.ZodNativeEnum<typeof Granularity> = z
  .nativeEnum(Granularity);
/** @internal */
export const Granularity$outboundSchema: z.ZodNativeEnum<typeof Granularity> =
  Granularity$inboundSchema;
