/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const Detail = {
  Auto: "auto",
  Low: "low",
  High: "high",
} as const;
export type Detail = ClosedEnum<typeof Detail>;

export type ImageURL = {
  url: string;
  detail?: Detail | undefined;
};

/** @internal */
export const Detail$inboundSchema: z.ZodNativeEnum<typeof Detail> = z
  .nativeEnum(Detail);
/** @internal */
export const Detail$outboundSchema: z.ZodNativeEnum<typeof Detail> =
  Detail$inboundSchema;

/** @internal */
export const ImageURL$inboundSchema: z.ZodType<
  ImageURL,
  z.ZodTypeDef,
  unknown
> = z.object({
  url: z.string(),
  detail: Detail$inboundSchema.optional(),
});
/** @internal */
export type ImageURL$Outbound = {
  url: string;
  detail?: string | undefined;
};

/** @internal */
export const ImageURL$outboundSchema: z.ZodType<
  ImageURL$Outbound,
  z.ZodTypeDef,
  ImageURL
> = z.object({
  url: z.string(),
  detail: Detail$outboundSchema.optional(),
});

export function imageURLToJSON(imageURL: ImageURL): string {
  return JSON.stringify(ImageURL$outboundSchema.parse(imageURL));
}
export function imageURLFromJSON(
  jsonString: string,
): SafeParseResult<ImageURL, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ImageURL$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ImageURL' from JSON`,
  );
}
