/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type JSONSchema = {
  name: string;
  description?: string | undefined;
  schema?: { [k: string]: any } | undefined;
  strict?: boolean | null | undefined;
};

/** @internal */
export const JSONSchema$inboundSchema: z.ZodType<
  JSONSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  description: z.string().optional(),
  schema: z.record(z.any()).optional(),
  strict: z.nullable(z.boolean()).optional(),
});
/** @internal */
export type JSONSchema$Outbound = {
  name: string;
  description?: string | undefined;
  schema?: { [k: string]: any } | undefined;
  strict?: boolean | null | undefined;
};

/** @internal */
export const JSONSchema$outboundSchema: z.ZodType<
  JSONSchema$Outbound,
  z.ZodTypeDef,
  JSONSchema
> = z.object({
  name: z.string(),
  description: z.string().optional(),
  schema: z.record(z.any()).optional(),
  strict: z.nullable(z.boolean()).optional(),
});

export function jsonSchemaToJSON(jsonSchema: JSONSchema): string {
  return JSON.stringify(JSONSchema$outboundSchema.parse(jsonSchema));
}
export function jsonSchemaFromJSON(
  jsonString: string,
): SafeParseResult<JSONSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => JSONSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'JSONSchema' from JSON`,
  );
}
