/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ListModelAliasesResponseItem = {
  /**
   * The ID of the model alias
   */
  id: string;
  /**
   * The name of the model alias
   */
  name: string;
  /**
   * Ordered list of model names to try as fallbacks
   */
  fallbackModels: Array<string>;
  /**
   * Optional description of the model alias
   */
  description?: string | null | undefined;
};

/** @internal */
export const ListModelAliasesResponseItem$inboundSchema: z.ZodType<
  ListModelAliasesResponseItem,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  fallback_models: z.array(z.string()),
  description: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "fallback_models": "fallbackModels",
  });
});

/** @internal */
export type ListModelAliasesResponseItem$Outbound = {
  id: string;
  name: string;
  fallback_models: Array<string>;
  description?: string | null | undefined;
};

/** @internal */
export const ListModelAliasesResponseItem$outboundSchema: z.ZodType<
  ListModelAliasesResponseItem$Outbound,
  z.ZodTypeDef,
  ListModelAliasesResponseItem
> = z.object({
  id: z.string(),
  name: z.string(),
  fallbackModels: z.array(z.string()),
  description: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    fallbackModels: "fallback_models",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListModelAliasesResponseItem$ {
  /** @deprecated use `ListModelAliasesResponseItem$inboundSchema` instead. */
  export const inboundSchema = ListModelAliasesResponseItem$inboundSchema;
  /** @deprecated use `ListModelAliasesResponseItem$outboundSchema` instead. */
  export const outboundSchema = ListModelAliasesResponseItem$outboundSchema;
  /** @deprecated use `ListModelAliasesResponseItem$Outbound` instead. */
  export type Outbound = ListModelAliasesResponseItem$Outbound;
}

export function listModelAliasesResponseItemToJSON(
  listModelAliasesResponseItem: ListModelAliasesResponseItem,
): string {
  return JSON.stringify(
    ListModelAliasesResponseItem$outboundSchema.parse(
      listModelAliasesResponseItem,
    ),
  );
}

export function listModelAliasesResponseItemFromJSON(
  jsonString: string,
): SafeParseResult<ListModelAliasesResponseItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListModelAliasesResponseItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListModelAliasesResponseItem' from JSON`,
  );
}
