/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Response model for listing rerank models.
 */
export type ListRerankModelsResponse = {
  /**
   * The hosting provider of the model
   */
  hostingProvider: string;
  /**
   * The name of the model
   */
  name: string;
  /**
   * The location of the model
   */
  location: string;
  /**
   * The cost in USD per rerank request
   */
  costPerRequest?: number | null | undefined;
};

/** @internal */
export const ListRerankModelsResponse$inboundSchema: z.ZodType<
  ListRerankModelsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  hosting_provider: z.string(),
  name: z.string(),
  location: z.string(),
  cost_per_request: z.nullable(z.number()).optional(),
}).transform((v) => {
  return remap$(v, {
    "hosting_provider": "hostingProvider",
    "cost_per_request": "costPerRequest",
  });
});
/** @internal */
export type ListRerankModelsResponse$Outbound = {
  hosting_provider: string;
  name: string;
  location: string;
  cost_per_request?: number | null | undefined;
};

/** @internal */
export const ListRerankModelsResponse$outboundSchema: z.ZodType<
  ListRerankModelsResponse$Outbound,
  z.ZodTypeDef,
  ListRerankModelsResponse
> = z.object({
  hostingProvider: z.string(),
  name: z.string(),
  location: z.string(),
  costPerRequest: z.nullable(z.number()).optional(),
}).transform((v) => {
  return remap$(v, {
    hostingProvider: "hosting_provider",
    costPerRequest: "cost_per_request",
  });
});

export function listRerankModelsResponseToJSON(
  listRerankModelsResponse: ListRerankModelsResponse,
): string {
  return JSON.stringify(
    ListRerankModelsResponse$outboundSchema.parse(listRerankModelsResponse),
  );
}
export function listRerankModelsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListRerankModelsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListRerankModelsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListRerankModelsResponse' from JSON`,
  );
}
