/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Mistral-specific OCR parameters.
 */
export type MistralOCRExtra = {
  /**
   * Whether to extract header content from pages
   */
  extractHeader?: boolean | null | undefined;
  /**
   * Whether to extract footer content from pages
   */
  extractFooter?: boolean | null | undefined;
  /**
   * Format for extracted tables: 'markdown' or 'html'
   */
  tableFormat?: string | null | undefined;
  /**
   * JSON schema for structured bounding box extraction
   */
  bboxAnnotationFormat?: { [k: string]: any } | null | undefined;
  /**
   * JSON schema for structured document extraction
   */
  documentAnnotationFormat?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const MistralOCRExtra$inboundSchema: z.ZodType<
  MistralOCRExtra,
  z.ZodTypeDef,
  unknown
> = z.object({
  extract_header: z.nullable(z.boolean()).optional(),
  extract_footer: z.nullable(z.boolean()).optional(),
  table_format: z.nullable(z.string()).optional(),
  bbox_annotation_format: z.nullable(z.record(z.any())).optional(),
  document_annotation_format: z.nullable(z.record(z.any())).optional(),
}).transform((v) => {
  return remap$(v, {
    "extract_header": "extractHeader",
    "extract_footer": "extractFooter",
    "table_format": "tableFormat",
    "bbox_annotation_format": "bboxAnnotationFormat",
    "document_annotation_format": "documentAnnotationFormat",
  });
});
/** @internal */
export type MistralOCRExtra$Outbound = {
  extract_header?: boolean | null | undefined;
  extract_footer?: boolean | null | undefined;
  table_format?: string | null | undefined;
  bbox_annotation_format?: { [k: string]: any } | null | undefined;
  document_annotation_format?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const MistralOCRExtra$outboundSchema: z.ZodType<
  MistralOCRExtra$Outbound,
  z.ZodTypeDef,
  MistralOCRExtra
> = z.object({
  extractHeader: z.nullable(z.boolean()).optional(),
  extractFooter: z.nullable(z.boolean()).optional(),
  tableFormat: z.nullable(z.string()).optional(),
  bboxAnnotationFormat: z.nullable(z.record(z.any())).optional(),
  documentAnnotationFormat: z.nullable(z.record(z.any())).optional(),
}).transform((v) => {
  return remap$(v, {
    extractHeader: "extract_header",
    extractFooter: "extract_footer",
    tableFormat: "table_format",
    bboxAnnotationFormat: "bbox_annotation_format",
    documentAnnotationFormat: "document_annotation_format",
  });
});

export function mistralOCRExtraToJSON(
  mistralOCRExtra: MistralOCRExtra,
): string {
  return JSON.stringify(MistralOCRExtra$outboundSchema.parse(mistralOCRExtra));
}
export function mistralOCRExtraFromJSON(
  jsonString: string,
): SafeParseResult<MistralOCRExtra, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MistralOCRExtra$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MistralOCRExtra' from JSON`,
  );
}
