/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Model = {
  name: string;
  extraHeaders?: { [k: string]: any } | null | undefined;
  options?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const Model$inboundSchema: z.ZodType<Model, z.ZodTypeDef, unknown> = z
  .object({
    name: z.string(),
    extra_headers: z.nullable(z.record(z.any())).optional(),
    options: z.nullable(z.record(z.any())).optional(),
  }).transform((v) => {
    return remap$(v, {
      "extra_headers": "extraHeaders",
    });
  });
/** @internal */
export type Model$Outbound = {
  name: string;
  extra_headers?: { [k: string]: any } | null | undefined;
  options?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const Model$outboundSchema: z.ZodType<
  Model$Outbound,
  z.ZodTypeDef,
  Model
> = z.object({
  name: z.string(),
  extraHeaders: z.nullable(z.record(z.any())).optional(),
  options: z.nullable(z.record(z.any())).optional(),
}).transform((v) => {
  return remap$(v, {
    extraHeaders: "extra_headers",
  });
});

export function modelToJSON(model: Model): string {
  return JSON.stringify(Model$outboundSchema.parse(model));
}
export function modelFromJSON(
  jsonString: string,
): SafeParseResult<Model, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Model$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Model' from JSON`,
  );
}
