/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * An image extracted from a page.
 */
export type OCRPageImage = {
  /**
   * Unique identifier for the image
   */
  id: string;
  /**
   * X coordinate of top-left corner
   */
  topLeftX?: number | null | undefined;
  /**
   * Y coordinate of top-left corner
   */
  topLeftY?: number | null | undefined;
  /**
   * X coordinate of bottom-right corner
   */
  bottomRightX?: number | null | undefined;
  /**
   * Y coordinate of bottom-right corner
   */
  bottomRightY?: number | null | undefined;
  /**
   * Base64-encoded image data (if include_image_base64=True)
   */
  imageBase64?: string | null | undefined;
};

/** @internal */
export const OCRPageImage$inboundSchema: z.ZodType<
  OCRPageImage,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  top_left_x: z.nullable(z.number().int()).optional(),
  top_left_y: z.nullable(z.number().int()).optional(),
  bottom_right_x: z.nullable(z.number().int()).optional(),
  bottom_right_y: z.nullable(z.number().int()).optional(),
  image_base64: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "top_left_x": "topLeftX",
    "top_left_y": "topLeftY",
    "bottom_right_x": "bottomRightX",
    "bottom_right_y": "bottomRightY",
    "image_base64": "imageBase64",
  });
});
/** @internal */
export type OCRPageImage$Outbound = {
  id: string;
  top_left_x?: number | null | undefined;
  top_left_y?: number | null | undefined;
  bottom_right_x?: number | null | undefined;
  bottom_right_y?: number | null | undefined;
  image_base64?: string | null | undefined;
};

/** @internal */
export const OCRPageImage$outboundSchema: z.ZodType<
  OCRPageImage$Outbound,
  z.ZodTypeDef,
  OCRPageImage
> = z.object({
  id: z.string(),
  topLeftX: z.nullable(z.number().int()).optional(),
  topLeftY: z.nullable(z.number().int()).optional(),
  bottomRightX: z.nullable(z.number().int()).optional(),
  bottomRightY: z.nullable(z.number().int()).optional(),
  imageBase64: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    topLeftX: "top_left_x",
    topLeftY: "top_left_y",
    bottomRightX: "bottom_right_x",
    bottomRightY: "bottom_right_y",
    imageBase64: "image_base64",
  });
});

export function ocrPageImageToJSON(ocrPageImage: OCRPageImage): string {
  return JSON.stringify(OCRPageImage$outboundSchema.parse(ocrPageImage));
}
export function ocrPageImageFromJSON(
  jsonString: string,
): SafeParseResult<OCRPageImage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OCRPageImage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OCRPageImage' from JSON`,
  );
}
