/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Dimensions of a processed page.
 */
export type OCRPageDimensions = {
  /**
   * DPI of the page
   */
  dpi?: number | null | undefined;
  /**
   * Height in pixels
   */
  height?: number | null | undefined;
  /**
   * Width in pixels
   */
  width?: number | null | undefined;
};

/** @internal */
export const OCRPageDimensions$inboundSchema: z.ZodType<
  OCRPageDimensions,
  z.ZodTypeDef,
  unknown
> = z.object({
  dpi: z.nullable(z.number().int()).optional(),
  height: z.nullable(z.number().int()).optional(),
  width: z.nullable(z.number().int()).optional(),
});
/** @internal */
export type OCRPageDimensions$Outbound = {
  dpi?: number | null | undefined;
  height?: number | null | undefined;
  width?: number | null | undefined;
};

/** @internal */
export const OCRPageDimensions$outboundSchema: z.ZodType<
  OCRPageDimensions$Outbound,
  z.ZodTypeDef,
  OCRPageDimensions
> = z.object({
  dpi: z.nullable(z.number().int()).optional(),
  height: z.nullable(z.number().int()).optional(),
  width: z.nullable(z.number().int()).optional(),
});

export function ocrPageDimensionsToJSON(
  ocrPageDimensions: OCRPageDimensions,
): string {
  return JSON.stringify(
    OCRPageDimensions$outboundSchema.parse(ocrPageDimensions),
  );
}
export function ocrPageDimensionsFromJSON(
  jsonString: string,
): SafeParseResult<OCRPageDimensions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OCRPageDimensions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OCRPageDimensions' from JSON`,
  );
}
