/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type OpenaiTypesChatChatCompletionNamedToolChoiceCustomParamCustom = {
  name: string;
};

/** @internal */
export const OpenaiTypesChatChatCompletionNamedToolChoiceCustomParamCustom$inboundSchema:
  z.ZodType<
    OpenaiTypesChatChatCompletionNamedToolChoiceCustomParamCustom,
    z.ZodTypeDef,
    unknown
  > = z.object({
    name: z.string(),
  });
/** @internal */
export type OpenaiTypesChatChatCompletionNamedToolChoiceCustomParamCustom$Outbound =
  {
    name: string;
  };

/** @internal */
export const OpenaiTypesChatChatCompletionNamedToolChoiceCustomParamCustom$outboundSchema:
  z.ZodType<
    OpenaiTypesChatChatCompletionNamedToolChoiceCustomParamCustom$Outbound,
    z.ZodTypeDef,
    OpenaiTypesChatChatCompletionNamedToolChoiceCustomParamCustom
  > = z.object({
    name: z.string(),
  });

export function openaiTypesChatChatCompletionNamedToolChoiceCustomParamCustomToJSON(
  openaiTypesChatChatCompletionNamedToolChoiceCustomParamCustom:
    OpenaiTypesChatChatCompletionNamedToolChoiceCustomParamCustom,
): string {
  return JSON.stringify(
    OpenaiTypesChatChatCompletionNamedToolChoiceCustomParamCustom$outboundSchema
      .parse(openaiTypesChatChatCompletionNamedToolChoiceCustomParamCustom),
  );
}
export function openaiTypesChatChatCompletionNamedToolChoiceCustomParamCustomFromJSON(
  jsonString: string,
): SafeParseResult<
  OpenaiTypesChatChatCompletionNamedToolChoiceCustomParamCustom,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OpenaiTypesChatChatCompletionNamedToolChoiceCustomParamCustom$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'OpenaiTypesChatChatCompletionNamedToolChoiceCustomParamCustom' from JSON`,
  );
}
