/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type OpenaiTypesChatChatCompletionAssistantMessageParamFunctionCall = {
  arguments: string;
  name: string;
};

/** @internal */
export const OpenaiTypesChatChatCompletionAssistantMessageParamFunctionCall$inboundSchema:
  z.ZodType<
    OpenaiTypesChatChatCompletionAssistantMessageParamFunctionCall,
    z.ZodTypeDef,
    unknown
  > = z.object({
    arguments: z.string(),
    name: z.string(),
  });

/** @internal */
export type OpenaiTypesChatChatCompletionAssistantMessageParamFunctionCall$Outbound =
  {
    arguments: string;
    name: string;
  };

/** @internal */
export const OpenaiTypesChatChatCompletionAssistantMessageParamFunctionCall$outboundSchema:
  z.ZodType<
    OpenaiTypesChatChatCompletionAssistantMessageParamFunctionCall$Outbound,
    z.ZodTypeDef,
    OpenaiTypesChatChatCompletionAssistantMessageParamFunctionCall
  > = z.object({
    arguments: z.string(),
    name: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OpenaiTypesChatChatCompletionAssistantMessageParamFunctionCall$ {
  /** @deprecated use `OpenaiTypesChatChatCompletionAssistantMessageParamFunctionCall$inboundSchema` instead. */
  export const inboundSchema =
    OpenaiTypesChatChatCompletionAssistantMessageParamFunctionCall$inboundSchema;
  /** @deprecated use `OpenaiTypesChatChatCompletionAssistantMessageParamFunctionCall$outboundSchema` instead. */
  export const outboundSchema =
    OpenaiTypesChatChatCompletionAssistantMessageParamFunctionCall$outboundSchema;
  /** @deprecated use `OpenaiTypesChatChatCompletionAssistantMessageParamFunctionCall$Outbound` instead. */
  export type Outbound =
    OpenaiTypesChatChatCompletionAssistantMessageParamFunctionCall$Outbound;
}

export function openaiTypesChatChatCompletionAssistantMessageParamFunctionCallToJSON(
  openaiTypesChatChatCompletionAssistantMessageParamFunctionCall:
    OpenaiTypesChatChatCompletionAssistantMessageParamFunctionCall,
): string {
  return JSON.stringify(
    OpenaiTypesChatChatCompletionAssistantMessageParamFunctionCall$outboundSchema
      .parse(openaiTypesChatChatCompletionAssistantMessageParamFunctionCall),
  );
}

export function openaiTypesChatChatCompletionAssistantMessageParamFunctionCallFromJSON(
  jsonString: string,
): SafeParseResult<
  OpenaiTypesChatChatCompletionAssistantMessageParamFunctionCall,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OpenaiTypesChatChatCompletionAssistantMessageParamFunctionCall$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'OpenaiTypesChatChatCompletionAssistantMessageParamFunctionCall' from JSON`,
  );
}
