/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  CustomFormatGrammar,
  CustomFormatGrammar$inboundSchema,
  CustomFormatGrammar$Outbound,
  CustomFormatGrammar$outboundSchema,
} from "./customformatgrammar.js";
import {
  CustomFormatText,
  CustomFormatText$inboundSchema,
  CustomFormatText$Outbound,
  CustomFormatText$outboundSchema,
} from "./customformattext.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Format = CustomFormatText | CustomFormatGrammar;

export type OpenaiTypesChatChatCompletionCustomToolParamCustom = {
  name: string;
  description?: string | undefined;
  format?: CustomFormatText | CustomFormatGrammar | undefined;
};

/** @internal */
export const Format$inboundSchema: z.ZodType<Format, z.ZodTypeDef, unknown> = z
  .union([CustomFormatText$inboundSchema, CustomFormatGrammar$inboundSchema]);
/** @internal */
export type Format$Outbound =
  | CustomFormatText$Outbound
  | CustomFormatGrammar$Outbound;

/** @internal */
export const Format$outboundSchema: z.ZodType<
  Format$Outbound,
  z.ZodTypeDef,
  Format
> = z.union([
  CustomFormatText$outboundSchema,
  CustomFormatGrammar$outboundSchema,
]);

export function formatToJSON(format: Format): string {
  return JSON.stringify(Format$outboundSchema.parse(format));
}
export function formatFromJSON(
  jsonString: string,
): SafeParseResult<Format, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Format$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Format' from JSON`,
  );
}

/** @internal */
export const OpenaiTypesChatChatCompletionCustomToolParamCustom$inboundSchema:
  z.ZodType<
    OpenaiTypesChatChatCompletionCustomToolParamCustom,
    z.ZodTypeDef,
    unknown
  > = z.object({
    name: z.string(),
    description: z.string().optional(),
    format: z.union([
      CustomFormatText$inboundSchema,
      CustomFormatGrammar$inboundSchema,
    ]).optional(),
  });
/** @internal */
export type OpenaiTypesChatChatCompletionCustomToolParamCustom$Outbound = {
  name: string;
  description?: string | undefined;
  format?: CustomFormatText$Outbound | CustomFormatGrammar$Outbound | undefined;
};

/** @internal */
export const OpenaiTypesChatChatCompletionCustomToolParamCustom$outboundSchema:
  z.ZodType<
    OpenaiTypesChatChatCompletionCustomToolParamCustom$Outbound,
    z.ZodTypeDef,
    OpenaiTypesChatChatCompletionCustomToolParamCustom
  > = z.object({
    name: z.string(),
    description: z.string().optional(),
    format: z.union([
      CustomFormatText$outboundSchema,
      CustomFormatGrammar$outboundSchema,
    ]).optional(),
  });

export function openaiTypesChatChatCompletionCustomToolParamCustomToJSON(
  openaiTypesChatChatCompletionCustomToolParamCustom:
    OpenaiTypesChatChatCompletionCustomToolParamCustom,
): string {
  return JSON.stringify(
    OpenaiTypesChatChatCompletionCustomToolParamCustom$outboundSchema.parse(
      openaiTypesChatChatCompletionCustomToolParamCustom,
    ),
  );
}
export function openaiTypesChatChatCompletionCustomToolParamCustomFromJSON(
  jsonString: string,
): SafeParseResult<
  OpenaiTypesChatChatCompletionCustomToolParamCustom,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      OpenaiTypesChatChatCompletionCustomToolParamCustom$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'OpenaiTypesChatChatCompletionCustomToolParamCustom' from JSON`,
  );
}
