/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ListTracesResponse,
  ListTracesResponse$inboundSchema,
  ListTracesResponse$Outbound,
  ListTracesResponse$outboundSchema,
} from "./listtracesresponse.js";
import {
  Meta,
  Meta$inboundSchema,
  Meta$Outbound,
  Meta$outboundSchema,
} from "./meta.js";

export type PaginatedResponseListTracesResponse = {
  meta: Meta;
  /**
   * List of items returned in the response
   */
  data: Array<ListTracesResponse>;
};

/** @internal */
export const PaginatedResponseListTracesResponse$inboundSchema: z.ZodType<
  PaginatedResponseListTracesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: Meta$inboundSchema,
  data: z.array(ListTracesResponse$inboundSchema),
});
/** @internal */
export type PaginatedResponseListTracesResponse$Outbound = {
  meta: Meta$Outbound;
  data: Array<ListTracesResponse$Outbound>;
};

/** @internal */
export const PaginatedResponseListTracesResponse$outboundSchema: z.ZodType<
  PaginatedResponseListTracesResponse$Outbound,
  z.ZodTypeDef,
  PaginatedResponseListTracesResponse
> = z.object({
  meta: Meta$outboundSchema,
  data: z.array(ListTracesResponse$outboundSchema),
});

export function paginatedResponseListTracesResponseToJSON(
  paginatedResponseListTracesResponse: PaginatedResponseListTracesResponse,
): string {
  return JSON.stringify(
    PaginatedResponseListTracesResponse$outboundSchema.parse(
      paginatedResponseListTracesResponse,
    ),
  );
}
export function paginatedResponseListTracesResponseFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedResponseListTracesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PaginatedResponseListTracesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedResponseListTracesResponse' from JSON`,
  );
}
