/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ListFunctionsResponseItem,
  ListFunctionsResponseItem$inboundSchema,
  ListFunctionsResponseItem$Outbound,
  ListFunctionsResponseItem$outboundSchema,
} from "./listfunctionsresponseitem.js";
import {
  Meta,
  Meta$inboundSchema,
  Meta$Outbound,
  Meta$outboundSchema,
} from "./meta.js";

export type PaginatedResponseListFunctionsResponseItem = {
  meta: Meta;
  /**
   * List of items returned in the response
   */
  data: Array<ListFunctionsResponseItem>;
};

/** @internal */
export const PaginatedResponseListFunctionsResponseItem$inboundSchema:
  z.ZodType<PaginatedResponseListFunctionsResponseItem, z.ZodTypeDef, unknown> =
    z.object({
      meta: Meta$inboundSchema,
      data: z.array(ListFunctionsResponseItem$inboundSchema),
    });
/** @internal */
export type PaginatedResponseListFunctionsResponseItem$Outbound = {
  meta: Meta$Outbound;
  data: Array<ListFunctionsResponseItem$Outbound>;
};

/** @internal */
export const PaginatedResponseListFunctionsResponseItem$outboundSchema:
  z.ZodType<
    PaginatedResponseListFunctionsResponseItem$Outbound,
    z.ZodTypeDef,
    PaginatedResponseListFunctionsResponseItem
  > = z.object({
    meta: Meta$outboundSchema,
    data: z.array(ListFunctionsResponseItem$outboundSchema),
  });

export function paginatedResponseListFunctionsResponseItemToJSON(
  paginatedResponseListFunctionsResponseItem:
    PaginatedResponseListFunctionsResponseItem,
): string {
  return JSON.stringify(
    PaginatedResponseListFunctionsResponseItem$outboundSchema.parse(
      paginatedResponseListFunctionsResponseItem,
    ),
  );
}
export function paginatedResponseListFunctionsResponseItemFromJSON(
  jsonString: string,
): SafeParseResult<
  PaginatedResponseListFunctionsResponseItem,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PaginatedResponseListFunctionsResponseItem$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PaginatedResponseListFunctionsResponseItem' from JSON`,
  );
}
