/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ListFilesResponse,
  ListFilesResponse$inboundSchema,
  ListFilesResponse$Outbound,
  ListFilesResponse$outboundSchema,
} from "./listfilesresponse.js";
import {
  Meta,
  Meta$inboundSchema,
  Meta$Outbound,
  Meta$outboundSchema,
} from "./meta.js";

export type PaginatedResponseListFilesResponse = {
  meta: Meta;
  /**
   * List of items returned in the response
   */
  data: Array<ListFilesResponse>;
};

/** @internal */
export const PaginatedResponseListFilesResponse$inboundSchema: z.ZodType<
  PaginatedResponseListFilesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: Meta$inboundSchema,
  data: z.array(ListFilesResponse$inboundSchema),
});
/** @internal */
export type PaginatedResponseListFilesResponse$Outbound = {
  meta: Meta$Outbound;
  data: Array<ListFilesResponse$Outbound>;
};

/** @internal */
export const PaginatedResponseListFilesResponse$outboundSchema: z.ZodType<
  PaginatedResponseListFilesResponse$Outbound,
  z.ZodTypeDef,
  PaginatedResponseListFilesResponse
> = z.object({
  meta: Meta$outboundSchema,
  data: z.array(ListFilesResponse$outboundSchema),
});

export function paginatedResponseListFilesResponseToJSON(
  paginatedResponseListFilesResponse: PaginatedResponseListFilesResponse,
): string {
  return JSON.stringify(
    PaginatedResponseListFilesResponse$outboundSchema.parse(
      paginatedResponseListFilesResponse,
    ),
  );
}
export function paginatedResponseListFilesResponseFromJSON(
  jsonString: string,
): SafeParseResult<PaginatedResponseListFilesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PaginatedResponseListFilesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaginatedResponseListFilesResponse' from JSON`,
  );
}
