/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  ListKnowledgeBasesResponse,
  ListKnowledgeBasesResponse$inboundSchema,
  ListKnowledgeBasesResponse$Outbound,
  ListKnowledgeBasesResponse$outboundSchema,
} from "./listknowledgebasesresponse.js";
import {
  Meta,
  Meta$inboundSchema,
  Meta$Outbound,
  Meta$outboundSchema,
} from "./meta.js";

export type PaginatedResponseListKnowledgeBasesResponse = {
  meta: Meta;
  /**
   * List of items returned in the response
   */
  data: Array<ListKnowledgeBasesResponse>;
};

/** @internal */
export const PaginatedResponseListKnowledgeBasesResponse$inboundSchema:
  z.ZodType<
    PaginatedResponseListKnowledgeBasesResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    meta: Meta$inboundSchema,
    data: z.array(ListKnowledgeBasesResponse$inboundSchema),
  });
/** @internal */
export type PaginatedResponseListKnowledgeBasesResponse$Outbound = {
  meta: Meta$Outbound;
  data: Array<ListKnowledgeBasesResponse$Outbound>;
};

/** @internal */
export const PaginatedResponseListKnowledgeBasesResponse$outboundSchema:
  z.ZodType<
    PaginatedResponseListKnowledgeBasesResponse$Outbound,
    z.ZodTypeDef,
    PaginatedResponseListKnowledgeBasesResponse
  > = z.object({
    meta: Meta$outboundSchema,
    data: z.array(ListKnowledgeBasesResponse$outboundSchema),
  });

export function paginatedResponseListKnowledgeBasesResponseToJSON(
  paginatedResponseListKnowledgeBasesResponse:
    PaginatedResponseListKnowledgeBasesResponse,
): string {
  return JSON.stringify(
    PaginatedResponseListKnowledgeBasesResponse$outboundSchema.parse(
      paginatedResponseListKnowledgeBasesResponse,
    ),
  );
}
export function paginatedResponseListKnowledgeBasesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PaginatedResponseListKnowledgeBasesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PaginatedResponseListKnowledgeBasesResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PaginatedResponseListKnowledgeBasesResponse' from JSON`,
  );
}
