/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type QueryDatasetEntriesResponse = {
  /**
   * The id of the dataset entry
   */
  id: string;
  /**
   * The input to the dataset entry
   */
  input: string;
  /**
   * The output to the dataset entry
   */
  output: string;
  /**
   * The expected output to the dataset entry, this is an optionally edited version of the output
   */
  expected?: string | null | undefined;
  /**
   * The comment to the dataset entry
   */
  comment?: string | null | undefined;
};

/** @internal */
export const QueryDatasetEntriesResponse$inboundSchema: z.ZodType<
  QueryDatasetEntriesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  input: z.string(),
  output: z.string(),
  expected: z.nullable(z.string()).optional(),
  comment: z.nullable(z.string()).optional(),
});

/** @internal */
export type QueryDatasetEntriesResponse$Outbound = {
  id: string;
  input: string;
  output: string;
  expected?: string | null | undefined;
  comment?: string | null | undefined;
};

/** @internal */
export const QueryDatasetEntriesResponse$outboundSchema: z.ZodType<
  QueryDatasetEntriesResponse$Outbound,
  z.ZodTypeDef,
  QueryDatasetEntriesResponse
> = z.object({
  id: z.string(),
  input: z.string(),
  output: z.string(),
  expected: z.nullable(z.string()).optional(),
  comment: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace QueryDatasetEntriesResponse$ {
  /** @deprecated use `QueryDatasetEntriesResponse$inboundSchema` instead. */
  export const inboundSchema = QueryDatasetEntriesResponse$inboundSchema;
  /** @deprecated use `QueryDatasetEntriesResponse$outboundSchema` instead. */
  export const outboundSchema = QueryDatasetEntriesResponse$outboundSchema;
  /** @deprecated use `QueryDatasetEntriesResponse$Outbound` instead. */
  export type Outbound = QueryDatasetEntriesResponse$Outbound;
}

export function queryDatasetEntriesResponseToJSON(
  queryDatasetEntriesResponse: QueryDatasetEntriesResponse,
): string {
  return JSON.stringify(
    QueryDatasetEntriesResponse$outboundSchema.parse(
      queryDatasetEntriesResponse,
    ),
  );
}

export function queryDatasetEntriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<QueryDatasetEntriesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryDatasetEntriesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryDatasetEntriesResponse' from JSON`,
  );
}
