/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Document to be reranked.
 */
export type RerankDocument = {
  /**
   * The text content of the document
   */
  text: string;
  /**
   * Optional metadata associated with the document
   */
  metadata?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const RerankDocument$inboundSchema: z.ZodType<
  RerankDocument,
  z.ZodTypeDef,
  unknown
> = z.object({
  text: z.string(),
  metadata: z.nullable(z.record(z.any())).optional(),
});
/** @internal */
export type RerankDocument$Outbound = {
  text: string;
  metadata?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const RerankDocument$outboundSchema: z.ZodType<
  RerankDocument$Outbound,
  z.ZodTypeDef,
  RerankDocument
> = z.object({
  text: z.string(),
  metadata: z.nullable(z.record(z.any())).optional(),
});

export function rerankDocumentToJSON(rerankDocument: RerankDocument): string {
  return JSON.stringify(RerankDocument$outboundSchema.parse(rerankDocument));
}
export function rerankDocumentFromJSON(
  jsonString: string,
): SafeParseResult<RerankDocument, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RerankDocument$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RerankDocument' from JSON`,
  );
}
