/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

/**
 * Cost information for reranking.
 */
export type RerankCost = {
  /**
   * Cost of the reranking request in USD
   */
  generation: number;
  /**
   * Platform fee in USD (percentage of generation cost)
   */
  platform: number;
  /**
   * Total cost in USD (generation + platform)
   */
  total: number;
};

/** @internal */
export const RerankCost$inboundSchema: z.ZodType<
  RerankCost,
  z.ZodTypeDef,
  unknown
> = z.object({
  generation: z.number(),
  platform: z.number(),
  total: z.number(),
});
/** @internal */
export type RerankCost$Outbound = {
  generation: number;
  platform: number;
  total: number;
};

/** @internal */
export const RerankCost$outboundSchema: z.ZodType<
  RerankCost$Outbound,
  z.ZodTypeDef,
  RerankCost
> = z.object({
  generation: z.number(),
  platform: z.number(),
  total: z.number(),
});

export function rerankCostToJSON(rerankCost: RerankCost): string {
  return JSON.stringify(RerankCost$outboundSchema.parse(rerankCost));
}
export function rerankCostFromJSON(
  jsonString: string,
): SafeParseResult<RerankCost, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RerankCost$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RerankCost' from JSON`,
  );
}
