/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type ResponseFormatText = {
  type?: "text" | undefined;
};

/** @internal */
export const ResponseFormatText$inboundSchema: z.ZodType<
  ResponseFormatText,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("text").default("text").optional(),
});

/** @internal */
export type ResponseFormatText$Outbound = {
  type: "text";
};

/** @internal */
export const ResponseFormatText$outboundSchema: z.ZodType<
  ResponseFormatText$Outbound,
  z.ZodTypeDef,
  ResponseFormatText
> = z.object({
  type: z.literal("text"),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResponseFormatText$ {
  /** @deprecated use `ResponseFormatText$inboundSchema` instead. */
  export const inboundSchema = ResponseFormatText$inboundSchema;
  /** @deprecated use `ResponseFormatText$outboundSchema` instead. */
  export const outboundSchema = ResponseFormatText$outboundSchema;
  /** @deprecated use `ResponseFormatText$Outbound` instead. */
  export type Outbound = ResponseFormatText$Outbound;
}

export function responseFormatTextToJSON(
  responseFormatText: ResponseFormatText,
): string {
  return JSON.stringify(
    ResponseFormatText$outboundSchema.parse(responseFormatText),
  );
}

export function responseFormatTextFromJSON(
  jsonString: string,
): SafeParseResult<ResponseFormatText, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseFormatText$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseFormatText' from JSON`,
  );
}
