/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  JSONSchema,
  JSONSchema$inboundSchema,
  JSONSchema$Outbound,
  JSONSchema$outboundSchema,
} from "./jsonschema.js";

export type ResponseFormatJSONSchema = {
  jsonSchema: JSONSchema;
  type: "json_schema";
};

/** @internal */
export const ResponseFormatJSONSchema$inboundSchema: z.ZodType<
  ResponseFormatJSONSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  json_schema: JSONSchema$inboundSchema,
  type: z.literal("json_schema"),
}).transform((v) => {
  return remap$(v, {
    "json_schema": "jsonSchema",
  });
});
/** @internal */
export type ResponseFormatJSONSchema$Outbound = {
  json_schema: JSONSchema$Outbound;
  type: "json_schema";
};

/** @internal */
export const ResponseFormatJSONSchema$outboundSchema: z.ZodType<
  ResponseFormatJSONSchema$Outbound,
  z.ZodTypeDef,
  ResponseFormatJSONSchema
> = z.object({
  jsonSchema: JSONSchema$outboundSchema,
  type: z.literal("json_schema"),
}).transform((v) => {
  return remap$(v, {
    jsonSchema: "json_schema",
  });
});

export function responseFormatJSONSchemaToJSON(
  responseFormatJSONSchema: ResponseFormatJSONSchema,
): string {
  return JSON.stringify(
    ResponseFormatJSONSchema$outboundSchema.parse(responseFormatJSONSchema),
  );
}
export function responseFormatJSONSchemaFromJSON(
  jsonString: string,
): SafeParseResult<ResponseFormatJSONSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseFormatJSONSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseFormatJSONSchema' from JSON`,
  );
}
