/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type TopLogprob = {
  token: string;
  bytes?: Array<number> | null | undefined;
  logprob: number;
  additionalProperties?: { [k: string]: any } | undefined;
};

/** @internal */
export const TopLogprob$inboundSchema: z.ZodType<
  TopLogprob,
  z.ZodTypeDef,
  unknown
> = collectExtraKeys$(
  z.object({
    token: z.string(),
    bytes: z.nullable(z.array(z.number().int())).optional(),
    logprob: z.number(),
  }).catchall(z.any()),
  "additionalProperties",
  true,
);
/** @internal */
export type TopLogprob$Outbound = {
  token: string;
  bytes?: Array<number> | null | undefined;
  logprob: number;
  [additionalProperties: string]: unknown;
};

/** @internal */
export const TopLogprob$outboundSchema: z.ZodType<
  TopLogprob$Outbound,
  z.ZodTypeDef,
  TopLogprob
> = z.object({
  token: z.string(),
  bytes: z.nullable(z.array(z.number().int())).optional(),
  logprob: z.number(),
  additionalProperties: z.record(z.any()).optional(),
}).transform((v) => {
  return {
    ...v.additionalProperties,
    ...remap$(v, {
      additionalProperties: null,
    }),
  };
});

export function topLogprobToJSON(topLogprob: TopLogprob): string {
  return JSON.stringify(TopLogprob$outboundSchema.parse(topLogprob));
}
export function topLogprobFromJSON(
  jsonString: string,
): SafeParseResult<TopLogprob, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TopLogprob$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TopLogprob' from JSON`,
  );
}
