/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type UpdateModelAliasRequest = {
  /**
   * The name of the model alias
   */
  name?: string | null | undefined;
  /**
   * Ordered list of model names to try as fallbacks
   */
  fallbackModels?: Array<string> | null | undefined;
  /**
   * Optional description of the model alias
   */
  description?: string | null | undefined;
};

/** @internal */
export const UpdateModelAliasRequest$inboundSchema: z.ZodType<
  UpdateModelAliasRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.nullable(z.string()).optional(),
  fallback_models: z.nullable(z.array(z.string())).optional(),
  description: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "fallback_models": "fallbackModels",
  });
});
/** @internal */
export type UpdateModelAliasRequest$Outbound = {
  name?: string | null | undefined;
  fallback_models?: Array<string> | null | undefined;
  description?: string | null | undefined;
};

/** @internal */
export const UpdateModelAliasRequest$outboundSchema: z.ZodType<
  UpdateModelAliasRequest$Outbound,
  z.ZodTypeDef,
  UpdateModelAliasRequest
> = z.object({
  name: z.nullable(z.string()).optional(),
  fallbackModels: z.nullable(z.array(z.string())).optional(),
  description: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    fallbackModels: "fallback_models",
  });
});

export function updateModelAliasRequestToJSON(
  updateModelAliasRequest: UpdateModelAliasRequest,
): string {
  return JSON.stringify(
    UpdateModelAliasRequest$outboundSchema.parse(updateModelAliasRequest),
  );
}
export function updateModelAliasRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateModelAliasRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateModelAliasRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateModelAliasRequest' from JSON`,
  );
}
