/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type UpdateDatasetEntryResponse = {
  /**
   * The id of the dataset entry
   */
  id: string;
  /**
   * The input to the dataset entry
   */
  input: string;
  /**
   * The output to the dataset entry
   */
  output: string;
  /**
   * The expected output to the dataset entry, this is an optionally edited version of the output
   */
  expected?: string | null | undefined;
  /**
   * The comment to the dataset entry
   */
  comment?: string | null | undefined;
};

/** @internal */
export const UpdateDatasetEntryResponse$inboundSchema: z.ZodType<
  UpdateDatasetEntryResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  input: z.string(),
  output: z.string(),
  expected: z.nullable(z.string()).optional(),
  comment: z.nullable(z.string()).optional(),
});

/** @internal */
export type UpdateDatasetEntryResponse$Outbound = {
  id: string;
  input: string;
  output: string;
  expected?: string | null | undefined;
  comment?: string | null | undefined;
};

/** @internal */
export const UpdateDatasetEntryResponse$outboundSchema: z.ZodType<
  UpdateDatasetEntryResponse$Outbound,
  z.ZodTypeDef,
  UpdateDatasetEntryResponse
> = z.object({
  id: z.string(),
  input: z.string(),
  output: z.string(),
  expected: z.nullable(z.string()).optional(),
  comment: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateDatasetEntryResponse$ {
  /** @deprecated use `UpdateDatasetEntryResponse$inboundSchema` instead. */
  export const inboundSchema = UpdateDatasetEntryResponse$inboundSchema;
  /** @deprecated use `UpdateDatasetEntryResponse$outboundSchema` instead. */
  export const outboundSchema = UpdateDatasetEntryResponse$outboundSchema;
  /** @deprecated use `UpdateDatasetEntryResponse$Outbound` instead. */
  export type Outbound = UpdateDatasetEntryResponse$Outbound;
}

export function updateDatasetEntryResponseToJSON(
  updateDatasetEntryResponse: UpdateDatasetEntryResponse,
): string {
  return JSON.stringify(
    UpdateDatasetEntryResponse$outboundSchema.parse(updateDatasetEntryResponse),
  );
}

export function updateDatasetEntryResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateDatasetEntryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateDatasetEntryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateDatasetEntryResponse' from JSON`,
  );
}
