/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  TModel,
  TModel$inboundSchema,
  TModel$Outbound,
  TModel$outboundSchema,
} from "./tmodel.js";

export type UpdateFunctionRequest = {
  /**
   * The name of the function. Must be unique within the project and can only contain letters, numbers, underscores and hyphens.
   */
  name?: string | null | undefined;
  /**
   * Optional description of the function. This is used to describe the function to a user.
   */
  description?: string | null | undefined;
  /**
   * The instructions for the function, this is the prompt that will be sent to the model to complete the task. Recommended to be concise and to the point
   */
  instructions?: string | null | undefined;
  /**
   * Optional input schema for the function. Can preferably include field descriptions to allow the model to reason about the input variables. Schema is validated against the input data and issues an error if it does not match. With the Opper SDKs you can define these schemas through libraries like Pydantic and Zod. For schemas with definitions, prefer using '$defs' and '#/$defs/...' references.
   */
  inputSchema?: { [k: string]: any } | null | undefined;
  /**
   * Optional output schema for the function. Can preferably include field descriptions to allow the model to reason about the output variables. Schema is validated against the output data and issues an error if it does not match. With the Opper SDKs you can define these schemas through libraries like Pydantic and Zod. For schemas with definitions, prefer using '$defs' and '#/$defs/...' references.
   */
  outputSchema?: { [k: string]: any } | null | undefined;
  /**
   * Optionally provide a model to use for completing the task. If not provided, a default model will be used. Currently the default model is `azure/gpt-4o-eu`
   */
  model?: TModel | null | undefined;
  /**
   * Optional configuration for the function.Configuration is a dictionary of key-value pairs that can be used to override the default configuration for the function.
   */
  configuration?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const UpdateFunctionRequest$inboundSchema: z.ZodType<
  UpdateFunctionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  instructions: z.nullable(z.string()).optional(),
  input_schema: z.nullable(z.record(z.any())).optional(),
  output_schema: z.nullable(z.record(z.any())).optional(),
  model: z.nullable(TModel$inboundSchema).optional(),
  configuration: z.nullable(z.record(z.any())).optional(),
}).transform((v) => {
  return remap$(v, {
    "input_schema": "inputSchema",
    "output_schema": "outputSchema",
  });
});

/** @internal */
export type UpdateFunctionRequest$Outbound = {
  name?: string | null | undefined;
  description?: string | null | undefined;
  instructions?: string | null | undefined;
  input_schema?: { [k: string]: any } | null | undefined;
  output_schema?: { [k: string]: any } | null | undefined;
  model?: TModel$Outbound | null | undefined;
  configuration?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const UpdateFunctionRequest$outboundSchema: z.ZodType<
  UpdateFunctionRequest$Outbound,
  z.ZodTypeDef,
  UpdateFunctionRequest
> = z.object({
  name: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  instructions: z.nullable(z.string()).optional(),
  inputSchema: z.nullable(z.record(z.any())).optional(),
  outputSchema: z.nullable(z.record(z.any())).optional(),
  model: z.nullable(TModel$outboundSchema).optional(),
  configuration: z.nullable(z.record(z.any())).optional(),
}).transform((v) => {
  return remap$(v, {
    inputSchema: "input_schema",
    outputSchema: "output_schema",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateFunctionRequest$ {
  /** @deprecated use `UpdateFunctionRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateFunctionRequest$inboundSchema;
  /** @deprecated use `UpdateFunctionRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateFunctionRequest$outboundSchema;
  /** @deprecated use `UpdateFunctionRequest$Outbound` instead. */
  export type Outbound = UpdateFunctionRequest$Outbound;
}

export function updateFunctionRequestToJSON(
  updateFunctionRequest: UpdateFunctionRequest,
): string {
  return JSON.stringify(
    UpdateFunctionRequest$outboundSchema.parse(updateFunctionRequest),
  );
}

export function updateFunctionRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateFunctionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateFunctionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateFunctionRequest' from JSON`,
  );
}
