/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type UpdateDatasetEntryRequest = {
  /**
   * The input to the dataset entry
   */
  input?: any | null | undefined;
  /**
   * The output to the dataset entry
   */
  output?: any | null | undefined;
  /**
   * The expected output to the dataset entry, this is an optionally edited version of the output
   */
  expected?: any | null | undefined;
  /**
   * The comment to the dataset entry
   */
  comment?: string | null | undefined;
};

/** @internal */
export const UpdateDatasetEntryRequest$inboundSchema: z.ZodType<
  UpdateDatasetEntryRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  input: z.nullable(z.any()).optional(),
  output: z.nullable(z.any()).optional(),
  expected: z.nullable(z.any()).optional(),
  comment: z.nullable(z.string()).optional(),
});
/** @internal */
export type UpdateDatasetEntryRequest$Outbound = {
  input?: any | null | undefined;
  output?: any | null | undefined;
  expected?: any | null | undefined;
  comment?: string | null | undefined;
};

/** @internal */
export const UpdateDatasetEntryRequest$outboundSchema: z.ZodType<
  UpdateDatasetEntryRequest$Outbound,
  z.ZodTypeDef,
  UpdateDatasetEntryRequest
> = z.object({
  input: z.nullable(z.any()).optional(),
  output: z.nullable(z.any()).optional(),
  expected: z.nullable(z.any()).optional(),
  comment: z.nullable(z.string()).optional(),
});

export function updateDatasetEntryRequestToJSON(
  updateDatasetEntryRequest: UpdateDatasetEntryRequest,
): string {
  return JSON.stringify(
    UpdateDatasetEntryRequest$outboundSchema.parse(updateDatasetEntryRequest),
  );
}
export function updateDatasetEntryRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateDatasetEntryRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateDatasetEntryRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateDatasetEntryRequest' from JSON`,
  );
}
